//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.25 at 07:43:28 PM IST 
//


package com.amway.integration.cis.los.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Created by aiu0256 on 5/22/15.
 * <p/>
 * <p/>
 * <p/>
 * Java class for abo complex type.
 * <p/>
 * <p/>
 * The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="abo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Aff" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ABONo" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "abo", propOrder = { "aff", "aboNo" })
public class Abo
{

	@XmlElement(name = "Aff")
	protected String aff;
	@XmlElement(name = "ABONo")
	protected Long aboNo;

	/**
	 * Gets the value of the aff property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getAff()
	{
		return aff;
	}

	/**
	 * Sets the value of the aff property.
	 *
	 * @param value allowed object is {@link String }
	 */
	public void setAff(final String value)
	{
		this.aff = value;
	}

	/**
	 * Gets the value of the aboNo property.
	 *
	 * @return possible object is {@link Long }
	 */
	public Long getABONo()
	{
		return aboNo;
	}

	/**
	 * Sets the value of the aboNo property.
	 *
	 * @param value allowed object is {@link Long }
	 */
	public void setABONo(final Long value)
	{
		this.aboNo = value;
	}

}
