/**
 * Magic DMS RESTful Services
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.amway.integration.cis.v3.swagger;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * BankUsage
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-10T10:19:16.797+03:00")
public class BankUsage   {
  @SerializedName("acctUseCode")
  private String acctUseCode = null;

  @SerializedName("useFlag")
  private String useFlag = null;

  public BankUsage acctUseCode(String acctUseCode) {
    this.acctUseCode = acctUseCode;
    return this;
  }

   /**
   * <a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=BAACU'>Reference to Bank Account Usage Codes</a>
   * @return acctUseCode
  **/
  @ApiModelProperty(example = "null", value = "<a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=BAACU'>Reference to Bank Account Usage Codes</a>")
  public String getAcctUseCode() {
    return acctUseCode;
  }

  public void setAcctUseCode(String acctUseCode) {
    this.acctUseCode = acctUseCode;
  }

  public BankUsage useFlag(String useFlag) {
    this.useFlag = useFlag;
    return this;
  }

   /**
   * Get useFlag
   * @return useFlag
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUseFlag() {
    return useFlag;
  }

  public void setUseFlag(String useFlag) {
    this.useFlag = useFlag;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BankUsage bankUsage = (BankUsage) o;
    return Objects.equals(this.acctUseCode, bankUsage.acctUseCode) &&
        Objects.equals(this.useFlag, bankUsage.useFlag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acctUseCode, useFlag);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BankUsage {\n");
    
    sb.append("    acctUseCode: ").append(toIndentedString(acctUseCode)).append("\n");
    sb.append("    useFlag: ").append(toIndentedString(useFlag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

