/**
 * Magic DMS RESTful Services
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.amway.integration.cis.v3.swagger;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;


/**
 * GroupErrorMessage
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-10T10:19:16.797+03:00")
public class GroupErrorMessage   {
  @SerializedName("fieldErrorList")
  private List<FieldErrorMessage> fieldErrorList = new ArrayList<FieldErrorMessage>();

  @SerializedName("id")
  private String id = null;

  public GroupErrorMessage fieldErrorList(List<FieldErrorMessage> fieldErrorList) {
    this.fieldErrorList = fieldErrorList;
    return this;
  }

  public GroupErrorMessage addFieldErrorListItem(FieldErrorMessage fieldErrorListItem) {
    this.fieldErrorList.add(fieldErrorListItem);
    return this;
  }

   /**
   * The field level error with its field name
   * @return fieldErrorList
  **/
  @ApiModelProperty(example = "null", value = "The field level error with its field name")
  public List<FieldErrorMessage> getFieldErrorList() {
    return fieldErrorList;
  }

  public void setFieldErrorList(List<FieldErrorMessage> fieldErrorList) {
    this.fieldErrorList = fieldErrorList;
  }

  public GroupErrorMessage id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GroupErrorMessage groupErrorMessage = (GroupErrorMessage) o;
    return Objects.equals(this.fieldErrorList, groupErrorMessage.fieldErrorList) &&
        Objects.equals(this.id, groupErrorMessage.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fieldErrorList, id);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GroupErrorMessage {\n");
    
    sb.append("    fieldErrorList: ").append(toIndentedString(fieldErrorList)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

