/**
 * Magic DMS RESTful Services
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.amway.integration.cis.v3.swagger;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * PersonalId
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-10T10:19:16.797+03:00")
public class PersonalId   {
  @SerializedName("personalIdTypeCd")
  private String personalIdTypeCd = null;

  @SerializedName("personalId")
  private String personalId = null;

  @SerializedName("expirationDate")
  private String expirationDate = null;

  @SerializedName("effectiveDate")
  private String effectiveDate = null;

  @SerializedName("countryPersonalId")
  private String countryPersonalId = null;

  public PersonalId personalIdTypeCd(String personalIdTypeCd) {
    this.personalIdTypeCd = personalIdTypeCd;
    return this;
  }

   /**
   * <a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=PRIDT'>Reference to Personal Type Code</a>
   * @return personalIdTypeCd
  **/
  @ApiModelProperty(example = "null", required = true, value = "<a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=PRIDT'>Reference to Personal Type Code</a>")
  public String getPersonalIdTypeCd() {
    return personalIdTypeCd;
  }

  public void setPersonalIdTypeCd(String personalIdTypeCd) {
    this.personalIdTypeCd = personalIdTypeCd;
  }

  public PersonalId personalId(String personalId) {
    this.personalId = personalId;
    return this;
  }

   /**
   * Get personalId
   * @return personalId
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getPersonalId() {
    return personalId;
  }

  public void setPersonalId(String personalId) {
    this.personalId = personalId;
  }

  public PersonalId expirationDate(String expirationDate) {
    this.expirationDate = expirationDate;
    return this;
  }

   /**
   * Date time in UTC such '2016-12-29T14:53:00-02:00'
   * @return expirationDate
  **/
  @ApiModelProperty(example = "null", value = "Date time in UTC such '2016-12-29T14:53:00-02:00'")
  public String getExpirationDate() {
    return expirationDate;
  }

  public void setExpirationDate(String expirationDate) {
    this.expirationDate = expirationDate;
  }

  public PersonalId effectiveDate(String effectiveDate) {
    this.effectiveDate = effectiveDate;
    return this;
  }

   /**
   * Date time in UTC such '2016-12-29T14:53:00-02:00'
   * @return effectiveDate
  **/
  @ApiModelProperty(example = "null", value = "Date time in UTC such '2016-12-29T14:53:00-02:00'")
  public String getEffectiveDate() {
    return effectiveDate;
  }

  public void setEffectiveDate(String effectiveDate) {
    this.effectiveDate = effectiveDate;
  }

  public PersonalId countryPersonalId(String countryPersonalId) {
    this.countryPersonalId = countryPersonalId;
    return this;
  }

   /**
   * Get countryPersonalId
   * @return countryPersonalId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCountryPersonalId() {
    return countryPersonalId;
  }

  public void setCountryPersonalId(String countryPersonalId) {
    this.countryPersonalId = countryPersonalId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PersonalId personalId = (PersonalId) o;
    return Objects.equals(this.personalIdTypeCd, personalId.personalIdTypeCd) &&
        Objects.equals(this.personalId, personalId.personalId) &&
        Objects.equals(this.expirationDate, personalId.expirationDate) &&
        Objects.equals(this.effectiveDate, personalId.effectiveDate) &&
        Objects.equals(this.countryPersonalId, personalId.countryPersonalId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(personalIdTypeCd, personalId, expirationDate, effectiveDate, countryPersonalId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PersonalId {\n");
    
    sb.append("    personalIdTypeCd: ").append(toIndentedString(personalIdTypeCd)).append("\n");
    sb.append("    personalId: ").append(toIndentedString(personalId)).append("\n");
    sb.append("    expirationDate: ").append(toIndentedString(expirationDate)).append("\n");
    sb.append("    effectiveDate: ").append(toIndentedString(effectiveDate)).append("\n");
    sb.append("    countryPersonalId: ").append(toIndentedString(countryPersonalId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

