/*
 * Magic DMS RESTful Services
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.amway.integration.cis.v3.swagger;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModelProperty;

/**
 * Account
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-06-29T12:31:49.813+03:00")
@JsonIgnoreProperties(ignoreUnknown = true)
public class Account implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("accountMst")
  private AccountMaster accountMst = null;

  @SerializedName("partyList")
  private List<Party> partyList = new ArrayList<Party>();

  @SerializedName("sponsor")
  private Sponsor sponsor = null;

  @SerializedName("blockPrivilegeList")
  private List<BlockPrivilege> blockPrivilegeList = new ArrayList<BlockPrivilege>();

  @SerializedName("accountBalanceList")
  private List<AccountBalance> accountBalanceList = new ArrayList<AccountBalance>();

  @SerializedName("subscriptionList")
  private List<Subscription> subscriptionList = new ArrayList<Subscription>();

  @SerializedName("missingInfoList")
  private List<MissingInfoDetail> missingInfoList = new ArrayList<MissingInfoDetail>();

  public Account accountMst(AccountMaster accountMst) {
    this.accountMst = accountMst;
    return this;
  }

  /**
   * Get accountMst
   * @return accountMst
   **/
  @ApiModelProperty(example = "null", value = "")
  public AccountMaster getAccountMst() {
    return accountMst;
  }

  public void setAccountMst(AccountMaster accountMst) {
    this.accountMst = accountMst;
  }

  public Account partyList(List<Party> partyList) {
    this.partyList = partyList;
    return this;
  }

  public Account addPartyListItem(Party partyListItem) {
    this.partyList.add(partyListItem);
    return this;
  }

  /**
   * Get partyList
   * @return partyList
   **/
  @ApiModelProperty(example = "null", value = "")
  public List<Party> getPartyList() {
    return partyList;
  }

  public void setPartyList(List<Party> partyList) {
    this.partyList = partyList;
  }

  public Account sponsor(Sponsor sponsor) {
    this.sponsor = sponsor;
    return this;
  }

  /**
   * Get sponsor
   * @return sponsor
   **/
  @ApiModelProperty(example = "null", value = "")
  public Sponsor getSponsor() {
    return sponsor;
  }

  public void setSponsor(Sponsor sponsor) {
    this.sponsor = sponsor;
  }

  public Account blockPrivilegeList(List<BlockPrivilege> blockPrivilegeList) {
    this.blockPrivilegeList = blockPrivilegeList;
    return this;
  }

  public Account addBlockPrivilegeListItem(BlockPrivilege blockPrivilegeListItem) {
    this.blockPrivilegeList.add(blockPrivilegeListItem);
    return this;
  }

  /**
   * Get blockPrivilegeList
   * @return blockPrivilegeList
   **/
  @ApiModelProperty(example = "null", value = "")
  public List<BlockPrivilege> getBlockPrivilegeList() {
    return blockPrivilegeList;
  }

  public void setBlockPrivilegeList(List<BlockPrivilege> blockPrivilegeList) {
    this.blockPrivilegeList = blockPrivilegeList;
  }

  public Account accountBalanceList(List<AccountBalance> accountBalanceList) {
    this.accountBalanceList = accountBalanceList;
    return this;
  }

  public Account addAccountBalanceListItem(AccountBalance accountBalanceListItem) {
    this.accountBalanceList.add(accountBalanceListItem);
    return this;
  }

  /**
   * Get accountBalanceList
   * @return accountBalanceList
   **/
  @ApiModelProperty(example = "null", value = "")
  public List<AccountBalance> getAccountBalanceList() {
    return accountBalanceList;
  }

  public void setAccountBalanceList(List<AccountBalance> accountBalanceList) {
    this.accountBalanceList = accountBalanceList;
  }

  public Account subscriptionList(List<Subscription> subscriptionList) {
    this.subscriptionList = subscriptionList;
    return this;
  }

  public Account addSubscriptionListItem(Subscription subscriptionListItem) {
    this.subscriptionList.add(subscriptionListItem);
    return this;
  }

  /**
   * Get subscriptionList
   * @return subscriptionList
   **/
  @ApiModelProperty(example = "null", value = "")
  public List<Subscription> getSubscriptionList() {
    return subscriptionList;
  }

  public void setSubscriptionList(List<Subscription> subscriptionList) {
    this.subscriptionList = subscriptionList;
  }

  public Account missingInfoList(List<MissingInfoDetail> missingInfoList) {
    this.missingInfoList = missingInfoList;
    return this;
  }

  public Account addMissingInfoListItem(MissingInfoDetail missingInfoListItem) {
    this.missingInfoList.add(missingInfoListItem);
    return this;
  }

  /**
   * Get missingInfoList
   * @return missingInfoList
   **/
  @ApiModelProperty(example = "null", value = "")
  public List<MissingInfoDetail> getMissingInfoList() {
    return missingInfoList;
  }

  public void setMissingInfoList(List<MissingInfoDetail> missingInfoList) {
    this.missingInfoList = missingInfoList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Account account = (Account) o;
    return Objects.equals(this.accountMst, account.accountMst) &&
          Objects.equals(this.partyList, account.partyList) &&
          Objects.equals(this.sponsor, account.sponsor) &&
          Objects.equals(this.blockPrivilegeList, account.blockPrivilegeList) &&
          Objects.equals(this.accountBalanceList, account.accountBalanceList) &&
          Objects.equals(this.subscriptionList, account.subscriptionList) &&
          Objects.equals(this.missingInfoList, account.missingInfoList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountMst, partyList, sponsor, blockPrivilegeList, accountBalanceList, subscriptionList, missingInfoList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Account {\n");

    sb.append("    accountMst: ").append(toIndentedString(accountMst)).append("\n");
    sb.append("    partyList: ").append(toIndentedString(partyList)).append("\n");
    sb.append("    sponsor: ").append(toIndentedString(sponsor)).append("\n");
    sb.append("    blockPrivilegeList: ").append(toIndentedString(blockPrivilegeList)).append("\n");
    sb.append("    accountBalanceList: ").append(toIndentedString(accountBalanceList)).append("\n");
    sb.append("    subscriptionList: ").append(toIndentedString(subscriptionList)).append("\n");
    sb.append("    missingInfoList: ").append(toIndentedString(missingInfoList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}