/**
 * Magic DMS RESTful Services
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.amway.integration.cis.v3.swagger;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * AccountContractDetail
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-10T10:19:16.797+03:00")
public class AccountContractDetail   {
  @SerializedName("contractId")
  private String contractId = null;

  @SerializedName("contractType")
  private String contractType = null;

  @SerializedName("effectiveStartDate")
  private String effectiveStartDate = null;

  @SerializedName("effectiveEndDate")
  private String effectiveEndDate = null;

  @SerializedName("acceptanceDate")
  private String acceptanceDate = null;

  @SerializedName("contractSignDate")
  private String contractSignDate = null;

  @SerializedName("sourceChannelId")
  private String sourceChannelId = null;

  @SerializedName("ipAddress")
  private String ipAddress = null;

  @SerializedName("esign")
  private String esign = null;

  @SerializedName("seqNo")
  private Long seqNo = null;

  @SerializedName("partyId")
  private Long partyId = null;

  public AccountContractDetail contractId(String contractId) {
    this.contractId = contractId;
    return this;
  }

   /**
   * Contract Id
   * @return contractId
  **/
  @ApiModelProperty(example = "null", required = true, value = "Contract Id")
  public String getContractId() {
    return contractId;
  }

  public void setContractId(String contractId) {
    this.contractId = contractId;
  }

  public AccountContractDetail contractType(String contractType) {
    this.contractType = contractType;
    return this;
  }

   /**
   * <a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=CNTID'>Reference to Contract Type Id</a>
   * @return contractType
  **/
  @ApiModelProperty(example = "null", required = true, value = "<a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=CNTID'>Reference to Contract Type Id</a>")
  public String getContractType() {
    return contractType;
  }

  public void setContractType(String contractType) {
    this.contractType = contractType;
  }

  public AccountContractDetail effectiveStartDate(String effectiveStartDate) {
    this.effectiveStartDate = effectiveStartDate;
    return this;
  }

   /**
   * Contract effective start date
   * @return effectiveStartDate
  **/
  @ApiModelProperty(example = "null", value = "Contract effective start date")
  public String getEffectiveStartDate() {
    return effectiveStartDate;
  }

  public void setEffectiveStartDate(String effectiveStartDate) {
    this.effectiveStartDate = effectiveStartDate;
  }

  public AccountContractDetail effectiveEndDate(String effectiveEndDate) {
    this.effectiveEndDate = effectiveEndDate;
    return this;
  }

   /**
   * Contract effective end date
   * @return effectiveEndDate
  **/
  @ApiModelProperty(example = "null", value = "Contract effective end date")
  public String getEffectiveEndDate() {
    return effectiveEndDate;
  }

  public void setEffectiveEndDate(String effectiveEndDate) {
    this.effectiveEndDate = effectiveEndDate;
  }

  public AccountContractDetail acceptanceDate(String acceptanceDate) {
    this.acceptanceDate = acceptanceDate;
    return this;
  }

   /**
   * Contract accept date
   * @return acceptanceDate
  **/
  @ApiModelProperty(example = "null", value = "Contract accept date")
  public String getAcceptanceDate() {
    return acceptanceDate;
  }

  public void setAcceptanceDate(String acceptanceDate) {
    this.acceptanceDate = acceptanceDate;
  }

  public AccountContractDetail contractSignDate(String contractSignDate) {
    this.contractSignDate = contractSignDate;
    return this;
  }

   /**
   * Contract sign date
   * @return contractSignDate
  **/
  @ApiModelProperty(example = "null", required = true, value = "Contract sign date")
  public String getContractSignDate() {
    return contractSignDate;
  }

  public void setContractSignDate(String contractSignDate) {
    this.contractSignDate = contractSignDate;
  }

  public AccountContractDetail sourceChannelId(String sourceChannelId) {
    this.sourceChannelId = sourceChannelId;
    return this;
  }

   /**
   * <a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=SRCHN'>Reference to Source channel Id</a>
   * @return sourceChannelId
  **/
  @ApiModelProperty(example = "null", required = true, value = "<a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=SRCHN'>Reference to Source channel Id</a>")
  public String getSourceChannelId() {
    return sourceChannelId;
  }

  public void setSourceChannelId(String sourceChannelId) {
    this.sourceChannelId = sourceChannelId;
  }

  public AccountContractDetail ipAddress(String ipAddress) {
    this.ipAddress = ipAddress;
    return this;
  }

   /**
   * Source IP address
   * @return ipAddress
  **/
  @ApiModelProperty(example = "null", value = "Source IP address")
  public String getIpAddress() {
    return ipAddress;
  }

  public void setIpAddress(String ipAddress) {
    this.ipAddress = ipAddress;
  }

  public AccountContractDetail esign(String esign) {
    this.esign = esign;
    return this;
  }

   /**
   * E-Signature
   * @return esign
  **/
  @ApiModelProperty(example = "null", required = true, value = "E-Signature")
  public String getEsign() {
    return esign;
  }

  public void setEsign(String esign) {
    this.esign = esign;
  }

  public AccountContractDetail seqNo(Long seqNo) {
    this.seqNo = seqNo;
    return this;
  }

   /**
   * Sequence number
   * @return seqNo
  **/
  @ApiModelProperty(example = "null", required = true, value = "Sequence number")
  public Long getSeqNo() {
    return seqNo;
  }

  public void setSeqNo(Long seqNo) {
    this.seqNo = seqNo;
  }

  public AccountContractDetail partyId(Long partyId) {
    this.partyId = partyId;
    return this;
  }

   /**
   * Party ID
   * @return partyId
  **/
  @ApiModelProperty(example = "null", value = "Party ID")
  public Long getPartyId() {
    return partyId;
  }

  public void setPartyId(Long partyId) {
    this.partyId = partyId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountContractDetail accountContractDetail = (AccountContractDetail) o;
    return Objects.equals(this.contractId, accountContractDetail.contractId) &&
        Objects.equals(this.contractType, accountContractDetail.contractType) &&
        Objects.equals(this.effectiveStartDate, accountContractDetail.effectiveStartDate) &&
        Objects.equals(this.effectiveEndDate, accountContractDetail.effectiveEndDate) &&
        Objects.equals(this.acceptanceDate, accountContractDetail.acceptanceDate) &&
        Objects.equals(this.contractSignDate, accountContractDetail.contractSignDate) &&
        Objects.equals(this.sourceChannelId, accountContractDetail.sourceChannelId) &&
        Objects.equals(this.ipAddress, accountContractDetail.ipAddress) &&
        Objects.equals(this.esign, accountContractDetail.esign) &&
        Objects.equals(this.seqNo, accountContractDetail.seqNo) &&
        Objects.equals(this.partyId, accountContractDetail.partyId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contractId, contractType, effectiveStartDate, effectiveEndDate, acceptanceDate, contractSignDate, sourceChannelId, ipAddress, esign, seqNo, partyId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountContractDetail {\n");
    
    sb.append("    contractId: ").append(toIndentedString(contractId)).append("\n");
    sb.append("    contractType: ").append(toIndentedString(contractType)).append("\n");
    sb.append("    effectiveStartDate: ").append(toIndentedString(effectiveStartDate)).append("\n");
    sb.append("    effectiveEndDate: ").append(toIndentedString(effectiveEndDate)).append("\n");
    sb.append("    acceptanceDate: ").append(toIndentedString(acceptanceDate)).append("\n");
    sb.append("    contractSignDate: ").append(toIndentedString(contractSignDate)).append("\n");
    sb.append("    sourceChannelId: ").append(toIndentedString(sourceChannelId)).append("\n");
    sb.append("    ipAddress: ").append(toIndentedString(ipAddress)).append("\n");
    sb.append("    esign: ").append(toIndentedString(esign)).append("\n");
    sb.append("    seqNo: ").append(toIndentedString(seqNo)).append("\n");
    sb.append("    partyId: ").append(toIndentedString(partyId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

