/**
 * Magic DMS RESTful Services
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.amway.integration.cis.v3.swagger;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * AccountSearchPhoneInfoRequest
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-10T10:19:16.797+03:00")
public class AccountSearchPhoneInfoRequest   {
  @SerializedName("phoneLocalNum")
  private String phoneLocalNum = null;

  @SerializedName("phoneCntryCd")
  private String phoneCntryCd = null;

  @SerializedName("phoneAreaCd")
  private String phoneAreaCd = null;

  public AccountSearchPhoneInfoRequest phoneLocalNum(String phoneLocalNum) {
    this.phoneLocalNum = phoneLocalNum;
    return this;
  }

   /**
   * phone local number
   * @return phoneLocalNum
  **/
  @ApiModelProperty(example = "null", required = true, value = "phone local number")
  public String getPhoneLocalNum() {
    return phoneLocalNum;
  }

  public void setPhoneLocalNum(String phoneLocalNum) {
    this.phoneLocalNum = phoneLocalNum;
  }

  public AccountSearchPhoneInfoRequest phoneCntryCd(String phoneCntryCd) {
    this.phoneCntryCd = phoneCntryCd;
    return this;
  }

   /**
   * phone country code
   * @return phoneCntryCd
  **/
  @ApiModelProperty(example = "null", value = "phone country code")
  public String getPhoneCntryCd() {
    return phoneCntryCd;
  }

  public void setPhoneCntryCd(String phoneCntryCd) {
    this.phoneCntryCd = phoneCntryCd;
  }

  public AccountSearchPhoneInfoRequest phoneAreaCd(String phoneAreaCd) {
    this.phoneAreaCd = phoneAreaCd;
    return this;
  }

   /**
   * phone area code
   * @return phoneAreaCd
  **/
  @ApiModelProperty(example = "null", value = "phone area code")
  public String getPhoneAreaCd() {
    return phoneAreaCd;
  }

  public void setPhoneAreaCd(String phoneAreaCd) {
    this.phoneAreaCd = phoneAreaCd;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountSearchPhoneInfoRequest accountSearchPhoneInfoRequest = (AccountSearchPhoneInfoRequest) o;
    return Objects.equals(this.phoneLocalNum, accountSearchPhoneInfoRequest.phoneLocalNum) &&
        Objects.equals(this.phoneCntryCd, accountSearchPhoneInfoRequest.phoneCntryCd) &&
        Objects.equals(this.phoneAreaCd, accountSearchPhoneInfoRequest.phoneAreaCd);
  }

  @Override
  public int hashCode() {
    return Objects.hash(phoneLocalNum, phoneCntryCd, phoneAreaCd);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountSearchPhoneInfoRequest {\n");
    
    sb.append("    phoneLocalNum: ").append(toIndentedString(phoneLocalNum)).append("\n");
    sb.append("    phoneCntryCd: ").append(toIndentedString(phoneCntryCd)).append("\n");
    sb.append("    phoneAreaCd: ").append(toIndentedString(phoneAreaCd)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

