/**
 * Magic DMS RESTful Services
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.amway.integration.cis.v3.swagger;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Affiliate
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-10T10:19:16.797+03:00")
public class Affiliate   {
  @SerializedName("salesPlanAff")
  private Integer salesPlanAff = null;

  @SerializedName("salesPlanAffName")
  private String salesPlanAffName = null;

  @SerializedName("salesPlanAffDesc")
  private String salesPlanAffDesc = null;

  @SerializedName("multiCurrencyFlag")
  private Boolean multiCurrencyFlag = null;

  @SerializedName("defaultCntryCd")
  private String defaultCntryCd = null;

  @SerializedName("defaultCompanyCd")
  private String defaultCompanyCd = null;

  @SerializedName("defaultCurrencyCd")
  private String defaultCurrencyCd = null;

  @SerializedName("affTimeZone")
  private String affTimeZone = null;

  @SerializedName("expirationCd")
  private String expirationCd = null;

  @SerializedName("defaultExpirationDate")
  private String defaultExpirationDate = null;

  @SerializedName("affAliasAboNum")
  private Long affAliasAboNum = null;

  public Affiliate salesPlanAff(Integer salesPlanAff) {
    this.salesPlanAff = salesPlanAff;
    return this;
  }

   /**
   * Get salesPlanAff
   * @return salesPlanAff
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getSalesPlanAff() {
    return salesPlanAff;
  }

  public void setSalesPlanAff(Integer salesPlanAff) {
    this.salesPlanAff = salesPlanAff;
  }

  public Affiliate salesPlanAffName(String salesPlanAffName) {
    this.salesPlanAffName = salesPlanAffName;
    return this;
  }

   /**
   * Get salesPlanAffName
   * @return salesPlanAffName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSalesPlanAffName() {
    return salesPlanAffName;
  }

  public void setSalesPlanAffName(String salesPlanAffName) {
    this.salesPlanAffName = salesPlanAffName;
  }

  public Affiliate salesPlanAffDesc(String salesPlanAffDesc) {
    this.salesPlanAffDesc = salesPlanAffDesc;
    return this;
  }

   /**
   * Get salesPlanAffDesc
   * @return salesPlanAffDesc
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSalesPlanAffDesc() {
    return salesPlanAffDesc;
  }

  public void setSalesPlanAffDesc(String salesPlanAffDesc) {
    this.salesPlanAffDesc = salesPlanAffDesc;
  }

  public Affiliate multiCurrencyFlag(Boolean multiCurrencyFlag) {
    this.multiCurrencyFlag = multiCurrencyFlag;
    return this;
  }

   /**
   * Get multiCurrencyFlag
   * @return multiCurrencyFlag
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getMultiCurrencyFlag() {
    return multiCurrencyFlag;
  }

  public void setMultiCurrencyFlag(Boolean multiCurrencyFlag) {
    this.multiCurrencyFlag = multiCurrencyFlag;
  }

  public Affiliate defaultCntryCd(String defaultCntryCd) {
    this.defaultCntryCd = defaultCntryCd;
    return this;
  }

   /**
   * Get defaultCntryCd
   * @return defaultCntryCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDefaultCntryCd() {
    return defaultCntryCd;
  }

  public void setDefaultCntryCd(String defaultCntryCd) {
    this.defaultCntryCd = defaultCntryCd;
  }

  public Affiliate defaultCompanyCd(String defaultCompanyCd) {
    this.defaultCompanyCd = defaultCompanyCd;
    return this;
  }

   /**
   * Get defaultCompanyCd
   * @return defaultCompanyCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDefaultCompanyCd() {
    return defaultCompanyCd;
  }

  public void setDefaultCompanyCd(String defaultCompanyCd) {
    this.defaultCompanyCd = defaultCompanyCd;
  }

  public Affiliate defaultCurrencyCd(String defaultCurrencyCd) {
    this.defaultCurrencyCd = defaultCurrencyCd;
    return this;
  }

   /**
   * Get defaultCurrencyCd
   * @return defaultCurrencyCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDefaultCurrencyCd() {
    return defaultCurrencyCd;
  }

  public void setDefaultCurrencyCd(String defaultCurrencyCd) {
    this.defaultCurrencyCd = defaultCurrencyCd;
  }

  public Affiliate affTimeZone(String affTimeZone) {
    this.affTimeZone = affTimeZone;
    return this;
  }

   /**
   * Get affTimeZone
   * @return affTimeZone
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAffTimeZone() {
    return affTimeZone;
  }

  public void setAffTimeZone(String affTimeZone) {
    this.affTimeZone = affTimeZone;
  }

  public Affiliate expirationCd(String expirationCd) {
    this.expirationCd = expirationCd;
    return this;
  }

   /**
   * Get expirationCd
   * @return expirationCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getExpirationCd() {
    return expirationCd;
  }

  public void setExpirationCd(String expirationCd) {
    this.expirationCd = expirationCd;
  }

  public Affiliate defaultExpirationDate(String defaultExpirationDate) {
    this.defaultExpirationDate = defaultExpirationDate;
    return this;
  }

   /**
   * Get defaultExpirationDate
   * @return defaultExpirationDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDefaultExpirationDate() {
    return defaultExpirationDate;
  }

  public void setDefaultExpirationDate(String defaultExpirationDate) {
    this.defaultExpirationDate = defaultExpirationDate;
  }

  public Affiliate affAliasAboNum(Long affAliasAboNum) {
    this.affAliasAboNum = affAliasAboNum;
    return this;
  }

   /**
   * Get affAliasAboNum
   * @return affAliasAboNum
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getAffAliasAboNum() {
    return affAliasAboNum;
  }

  public void setAffAliasAboNum(Long affAliasAboNum) {
    this.affAliasAboNum = affAliasAboNum;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Affiliate affiliate = (Affiliate) o;
    return Objects.equals(this.salesPlanAff, affiliate.salesPlanAff) &&
        Objects.equals(this.salesPlanAffName, affiliate.salesPlanAffName) &&
        Objects.equals(this.salesPlanAffDesc, affiliate.salesPlanAffDesc) &&
        Objects.equals(this.multiCurrencyFlag, affiliate.multiCurrencyFlag) &&
        Objects.equals(this.defaultCntryCd, affiliate.defaultCntryCd) &&
        Objects.equals(this.defaultCompanyCd, affiliate.defaultCompanyCd) &&
        Objects.equals(this.defaultCurrencyCd, affiliate.defaultCurrencyCd) &&
        Objects.equals(this.affTimeZone, affiliate.affTimeZone) &&
        Objects.equals(this.expirationCd, affiliate.expirationCd) &&
        Objects.equals(this.defaultExpirationDate, affiliate.defaultExpirationDate) &&
        Objects.equals(this.affAliasAboNum, affiliate.affAliasAboNum);
  }

  @Override
  public int hashCode() {
    return Objects.hash(salesPlanAff, salesPlanAffName, salesPlanAffDesc, multiCurrencyFlag, defaultCntryCd, defaultCompanyCd, defaultCurrencyCd, affTimeZone, expirationCd, defaultExpirationDate, affAliasAboNum);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Affiliate {\n");
    
    sb.append("    salesPlanAff: ").append(toIndentedString(salesPlanAff)).append("\n");
    sb.append("    salesPlanAffName: ").append(toIndentedString(salesPlanAffName)).append("\n");
    sb.append("    salesPlanAffDesc: ").append(toIndentedString(salesPlanAffDesc)).append("\n");
    sb.append("    multiCurrencyFlag: ").append(toIndentedString(multiCurrencyFlag)).append("\n");
    sb.append("    defaultCntryCd: ").append(toIndentedString(defaultCntryCd)).append("\n");
    sb.append("    defaultCompanyCd: ").append(toIndentedString(defaultCompanyCd)).append("\n");
    sb.append("    defaultCurrencyCd: ").append(toIndentedString(defaultCurrencyCd)).append("\n");
    sb.append("    affTimeZone: ").append(toIndentedString(affTimeZone)).append("\n");
    sb.append("    expirationCd: ").append(toIndentedString(expirationCd)).append("\n");
    sb.append("    defaultExpirationDate: ").append(toIndentedString(defaultExpirationDate)).append("\n");
    sb.append("    affAliasAboNum: ").append(toIndentedString(affAliasAboNum)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

