/**
 * Magic DMS RESTful Services
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.amway.integration.cis.v3.swagger;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * AmwayAccount
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-10T10:19:16.797+03:00")
public class AmwayAccount   {
  @SerializedName("accountId")
  private Long accountId = null;

  @SerializedName("accountName")
  private String accountName = null;

  @SerializedName("accountSubTypeCd")
  private String accountSubTypeCd = null;

  @SerializedName("cntryCd")
  private String cntryCd = null;

  @SerializedName("statusCd")
  private String statusCd = null;

  @SerializedName("partyId")
  private String partyId = null;

  @SerializedName("salesPlanAff")
  private String salesPlanAff = null;

  @SerializedName("globalPartyId")
  private String globalPartyId = null;

  @SerializedName("roleCd")
  private String roleCd = null;

  public AmwayAccount accountId(Long accountId) {
    this.accountId = accountId;
    return this;
  }

   /**
   * Get accountId
   * @return accountId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getAccountId() {
    return accountId;
  }

  public void setAccountId(Long accountId) {
    this.accountId = accountId;
  }

  public AmwayAccount accountName(String accountName) {
    this.accountName = accountName;
    return this;
  }

   /**
   * Get accountName
   * @return accountName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAccountName() {
    return accountName;
  }

  public void setAccountName(String accountName) {
    this.accountName = accountName;
  }

  public AmwayAccount accountSubTypeCd(String accountSubTypeCd) {
    this.accountSubTypeCd = accountSubTypeCd;
    return this;
  }

   /**
   * Get accountSubTypeCd
   * @return accountSubTypeCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAccountSubTypeCd() {
    return accountSubTypeCd;
  }

  public void setAccountSubTypeCd(String accountSubTypeCd) {
    this.accountSubTypeCd = accountSubTypeCd;
  }

  public AmwayAccount cntryCd(String cntryCd) {
    this.cntryCd = cntryCd;
    return this;
  }

   /**
   * Get cntryCd
   * @return cntryCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCntryCd() {
    return cntryCd;
  }

  public void setCntryCd(String cntryCd) {
    this.cntryCd = cntryCd;
  }

  public AmwayAccount statusCd(String statusCd) {
    this.statusCd = statusCd;
    return this;
  }

   /**
   * Get statusCd
   * @return statusCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStatusCd() {
    return statusCd;
  }

  public void setStatusCd(String statusCd) {
    this.statusCd = statusCd;
  }

  public AmwayAccount partyId(String partyId) {
    this.partyId = partyId;
    return this;
  }

   /**
   * Get partyId
   * @return partyId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPartyId() {
    return partyId;
  }

  public void setPartyId(String partyId) {
    this.partyId = partyId;
  }

  public AmwayAccount salesPlanAff(String salesPlanAff) {
    this.salesPlanAff = salesPlanAff;
    return this;
  }

   /**
   * Get salesPlanAff
   * @return salesPlanAff
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSalesPlanAff() {
    return salesPlanAff;
  }

  public void setSalesPlanAff(String salesPlanAff) {
    this.salesPlanAff = salesPlanAff;
  }

  public AmwayAccount globalPartyId(String globalPartyId) {
    this.globalPartyId = globalPartyId;
    return this;
  }

   /**
   * Get globalPartyId
   * @return globalPartyId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGlobalPartyId() {
    return globalPartyId;
  }

  public void setGlobalPartyId(String globalPartyId) {
    this.globalPartyId = globalPartyId;
  }

  public AmwayAccount roleCd(String roleCd) {
    this.roleCd = roleCd;
    return this;
  }

   /**
   * Get roleCd
   * @return roleCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRoleCd() {
    return roleCd;
  }

  public void setRoleCd(String roleCd) {
    this.roleCd = roleCd;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AmwayAccount amwayAccount = (AmwayAccount) o;
    return Objects.equals(this.accountId, amwayAccount.accountId) &&
        Objects.equals(this.accountName, amwayAccount.accountName) &&
        Objects.equals(this.accountSubTypeCd, amwayAccount.accountSubTypeCd) &&
        Objects.equals(this.cntryCd, amwayAccount.cntryCd) &&
        Objects.equals(this.statusCd, amwayAccount.statusCd) &&
        Objects.equals(this.partyId, amwayAccount.partyId) &&
        Objects.equals(this.salesPlanAff, amwayAccount.salesPlanAff) &&
        Objects.equals(this.globalPartyId, amwayAccount.globalPartyId) &&
        Objects.equals(this.roleCd, amwayAccount.roleCd);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, accountName, accountSubTypeCd, cntryCd, statusCd, partyId, salesPlanAff, globalPartyId, roleCd);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AmwayAccount {\n");
    
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    accountName: ").append(toIndentedString(accountName)).append("\n");
    sb.append("    accountSubTypeCd: ").append(toIndentedString(accountSubTypeCd)).append("\n");
    sb.append("    cntryCd: ").append(toIndentedString(cntryCd)).append("\n");
    sb.append("    statusCd: ").append(toIndentedString(statusCd)).append("\n");
    sb.append("    partyId: ").append(toIndentedString(partyId)).append("\n");
    sb.append("    salesPlanAff: ").append(toIndentedString(salesPlanAff)).append("\n");
    sb.append("    globalPartyId: ").append(toIndentedString(globalPartyId)).append("\n");
    sb.append("    roleCd: ").append(toIndentedString(roleCd)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

