/**
 * Magic DMS RESTful Services
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.amway.integration.cis.v3.swagger;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;


/**
 * BankAccount
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-10T10:19:16.797+03:00")
public class BankAccount   {
  @SerializedName("bankAcctId")
  private String bankAcctId = null;

  @SerializedName("partyId")
  private String partyId = null;

  @SerializedName("bankAcctTypeCd")
  private String bankAcctTypeCd = null;

  @SerializedName("bankAcctNum")
  private String bankAcctNum = null;

  @SerializedName("effectiveStartDate")
  private String effectiveStartDate = null;

  @SerializedName("effectiveEndDate")
  private String effectiveEndDate = null;

  @SerializedName("primaryRoutingNum")
  private String primaryRoutingNum = null;

  @SerializedName("issuingBankId")
  private String issuingBankId = null;

  @SerializedName("issuingBankName")
  private String issuingBankName = null;

  @SerializedName("bankBranchCode")
  private String bankBranchCode = null;

  @SerializedName("bankBranchName")
  private String bankBranchName = null;

  @SerializedName("secondaryRoutingNum")
  private String secondaryRoutingNum = null;

  @SerializedName("bankAcctHolderName")
  private String bankAcctHolderName = null;

  @SerializedName("bankAcctName")
  private String bankAcctName = null;

  @SerializedName("currencyCd")
  private String currencyCd = null;

  @SerializedName("bankCntryCd")
  private String bankCntryCd = null;

  @SerializedName("acctUsageList")
  private List<BankUsage> acctUsageList = new ArrayList<BankUsage>();

  public BankAccount bankAcctId(String bankAcctId) {
    this.bankAcctId = bankAcctId;
    return this;
  }

   /**
   * Get bankAcctId
   * @return bankAcctId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBankAcctId() {
    return bankAcctId;
  }

  public void setBankAcctId(String bankAcctId) {
    this.bankAcctId = bankAcctId;
  }

  public BankAccount partyId(String partyId) {
    this.partyId = partyId;
    return this;
  }

   /**
   * Get partyId
   * @return partyId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPartyId() {
    return partyId;
  }

  public void setPartyId(String partyId) {
    this.partyId = partyId;
  }

  public BankAccount bankAcctTypeCd(String bankAcctTypeCd) {
    this.bankAcctTypeCd = bankAcctTypeCd;
    return this;
  }

   /**
   * <a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=BATCD'>Reference to Bank Account Type Codes</a>
   * @return bankAcctTypeCd
  **/
  @ApiModelProperty(example = "null", required = true, value = "<a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=BATCD'>Reference to Bank Account Type Codes</a>")
  public String getBankAcctTypeCd() {
    return bankAcctTypeCd;
  }

  public void setBankAcctTypeCd(String bankAcctTypeCd) {
    this.bankAcctTypeCd = bankAcctTypeCd;
  }

  public BankAccount bankAcctNum(String bankAcctNum) {
    this.bankAcctNum = bankAcctNum;
    return this;
  }

   /**
   * Get bankAcctNum
   * @return bankAcctNum
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBankAcctNum() {
    return bankAcctNum;
  }

  public void setBankAcctNum(String bankAcctNum) {
    this.bankAcctNum = bankAcctNum;
  }

  public BankAccount effectiveStartDate(String effectiveStartDate) {
    this.effectiveStartDate = effectiveStartDate;
    return this;
  }

   /**
   * Get effectiveStartDate
   * @return effectiveStartDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEffectiveStartDate() {
    return effectiveStartDate;
  }

  public void setEffectiveStartDate(String effectiveStartDate) {
    this.effectiveStartDate = effectiveStartDate;
  }

  public BankAccount effectiveEndDate(String effectiveEndDate) {
    this.effectiveEndDate = effectiveEndDate;
    return this;
  }

   /**
   * Get effectiveEndDate
   * @return effectiveEndDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEffectiveEndDate() {
    return effectiveEndDate;
  }

  public void setEffectiveEndDate(String effectiveEndDate) {
    this.effectiveEndDate = effectiveEndDate;
  }

  public BankAccount primaryRoutingNum(String primaryRoutingNum) {
    this.primaryRoutingNum = primaryRoutingNum;
    return this;
  }

   /**
   * Get primaryRoutingNum
   * @return primaryRoutingNum
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPrimaryRoutingNum() {
    return primaryRoutingNum;
  }

  public void setPrimaryRoutingNum(String primaryRoutingNum) {
    this.primaryRoutingNum = primaryRoutingNum;
  }

  public BankAccount issuingBankId(String issuingBankId) {
    this.issuingBankId = issuingBankId;
    return this;
  }

   /**
   * Get issuingBankId
   * @return issuingBankId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIssuingBankId() {
    return issuingBankId;
  }

  public void setIssuingBankId(String issuingBankId) {
    this.issuingBankId = issuingBankId;
  }

  public BankAccount issuingBankName(String issuingBankName) {
    this.issuingBankName = issuingBankName;
    return this;
  }

   /**
   * Get issuingBankName
   * @return issuingBankName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIssuingBankName() {
    return issuingBankName;
  }

  public void setIssuingBankName(String issuingBankName) {
    this.issuingBankName = issuingBankName;
  }

  public BankAccount bankBranchCode(String bankBranchCode) {
    this.bankBranchCode = bankBranchCode;
    return this;
  }

   /**
   * Get bankBranchCode
   * @return bankBranchCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBankBranchCode() {
    return bankBranchCode;
  }

  public void setBankBranchCode(String bankBranchCode) {
    this.bankBranchCode = bankBranchCode;
  }

  public BankAccount bankBranchName(String bankBranchName) {
    this.bankBranchName = bankBranchName;
    return this;
  }

   /**
   * Get bankBranchName
   * @return bankBranchName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBankBranchName() {
    return bankBranchName;
  }

  public void setBankBranchName(String bankBranchName) {
    this.bankBranchName = bankBranchName;
  }

  public BankAccount secondaryRoutingNum(String secondaryRoutingNum) {
    this.secondaryRoutingNum = secondaryRoutingNum;
    return this;
  }

   /**
   * Get secondaryRoutingNum
   * @return secondaryRoutingNum
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSecondaryRoutingNum() {
    return secondaryRoutingNum;
  }

  public void setSecondaryRoutingNum(String secondaryRoutingNum) {
    this.secondaryRoutingNum = secondaryRoutingNum;
  }

  public BankAccount bankAcctHolderName(String bankAcctHolderName) {
    this.bankAcctHolderName = bankAcctHolderName;
    return this;
  }

   /**
   * Get bankAcctHolderName
   * @return bankAcctHolderName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBankAcctHolderName() {
    return bankAcctHolderName;
  }

  public void setBankAcctHolderName(String bankAcctHolderName) {
    this.bankAcctHolderName = bankAcctHolderName;
  }

  public BankAccount bankAcctName(String bankAcctName) {
    this.bankAcctName = bankAcctName;
    return this;
  }

   /**
   * Get bankAcctName
   * @return bankAcctName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBankAcctName() {
    return bankAcctName;
  }

  public void setBankAcctName(String bankAcctName) {
    this.bankAcctName = bankAcctName;
  }

  public BankAccount currencyCd(String currencyCd) {
    this.currencyCd = currencyCd;
    return this;
  }

   /**
   * Get currencyCd
   * @return currencyCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCurrencyCd() {
    return currencyCd;
  }

  public void setCurrencyCd(String currencyCd) {
    this.currencyCd = currencyCd;
  }

  public BankAccount bankCntryCd(String bankCntryCd) {
    this.bankCntryCd = bankCntryCd;
    return this;
  }

   /**
   * Get bankCntryCd
   * @return bankCntryCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBankCntryCd() {
    return bankCntryCd;
  }

  public void setBankCntryCd(String bankCntryCd) {
    this.bankCntryCd = bankCntryCd;
  }

  public BankAccount acctUsageList(List<BankUsage> acctUsageList) {
    this.acctUsageList = acctUsageList;
    return this;
  }

  public BankAccount addAcctUsageListItem(BankUsage acctUsageListItem) {
    this.acctUsageList.add(acctUsageListItem);
    return this;
  }

   /**
   * Get acctUsageList
   * @return acctUsageList
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<BankUsage> getAcctUsageList() {
    return acctUsageList;
  }

  public void setAcctUsageList(List<BankUsage> acctUsageList) {
    this.acctUsageList = acctUsageList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BankAccount bankAccount = (BankAccount) o;
    return Objects.equals(this.bankAcctId, bankAccount.bankAcctId) &&
        Objects.equals(this.partyId, bankAccount.partyId) &&
        Objects.equals(this.bankAcctTypeCd, bankAccount.bankAcctTypeCd) &&
        Objects.equals(this.bankAcctNum, bankAccount.bankAcctNum) &&
        Objects.equals(this.effectiveStartDate, bankAccount.effectiveStartDate) &&
        Objects.equals(this.effectiveEndDate, bankAccount.effectiveEndDate) &&
        Objects.equals(this.primaryRoutingNum, bankAccount.primaryRoutingNum) &&
        Objects.equals(this.issuingBankId, bankAccount.issuingBankId) &&
        Objects.equals(this.issuingBankName, bankAccount.issuingBankName) &&
        Objects.equals(this.bankBranchCode, bankAccount.bankBranchCode) &&
        Objects.equals(this.bankBranchName, bankAccount.bankBranchName) &&
        Objects.equals(this.secondaryRoutingNum, bankAccount.secondaryRoutingNum) &&
        Objects.equals(this.bankAcctHolderName, bankAccount.bankAcctHolderName) &&
        Objects.equals(this.bankAcctName, bankAccount.bankAcctName) &&
        Objects.equals(this.currencyCd, bankAccount.currencyCd) &&
        Objects.equals(this.bankCntryCd, bankAccount.bankCntryCd) &&
        Objects.equals(this.acctUsageList, bankAccount.acctUsageList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bankAcctId, partyId, bankAcctTypeCd, bankAcctNum, effectiveStartDate, effectiveEndDate, primaryRoutingNum, issuingBankId, issuingBankName, bankBranchCode, bankBranchName, secondaryRoutingNum, bankAcctHolderName, bankAcctName, currencyCd, bankCntryCd, acctUsageList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BankAccount {\n");
    
    sb.append("    bankAcctId: ").append(toIndentedString(bankAcctId)).append("\n");
    sb.append("    partyId: ").append(toIndentedString(partyId)).append("\n");
    sb.append("    bankAcctTypeCd: ").append(toIndentedString(bankAcctTypeCd)).append("\n");
    sb.append("    bankAcctNum: ").append(toIndentedString(bankAcctNum)).append("\n");
    sb.append("    effectiveStartDate: ").append(toIndentedString(effectiveStartDate)).append("\n");
    sb.append("    effectiveEndDate: ").append(toIndentedString(effectiveEndDate)).append("\n");
    sb.append("    primaryRoutingNum: ").append(toIndentedString(primaryRoutingNum)).append("\n");
    sb.append("    issuingBankId: ").append(toIndentedString(issuingBankId)).append("\n");
    sb.append("    issuingBankName: ").append(toIndentedString(issuingBankName)).append("\n");
    sb.append("    bankBranchCode: ").append(toIndentedString(bankBranchCode)).append("\n");
    sb.append("    bankBranchName: ").append(toIndentedString(bankBranchName)).append("\n");
    sb.append("    secondaryRoutingNum: ").append(toIndentedString(secondaryRoutingNum)).append("\n");
    sb.append("    bankAcctHolderName: ").append(toIndentedString(bankAcctHolderName)).append("\n");
    sb.append("    bankAcctName: ").append(toIndentedString(bankAcctName)).append("\n");
    sb.append("    currencyCd: ").append(toIndentedString(currencyCd)).append("\n");
    sb.append("    bankCntryCd: ").append(toIndentedString(bankCntryCd)).append("\n");
    sb.append("    acctUsageList: ").append(toIndentedString(acctUsageList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

