/**
 * Magic DMS RESTful Services
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.amway.integration.cis.v3.swagger;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * BlockPrivilege
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-10T10:19:16.797+03:00")
@JsonIgnoreProperties(ignoreUnknown=true)
public class BlockPrivilege   {
  @SerializedName("blockPrivTypeId")
  private String blockPrivTypeId = null;

  @SerializedName("effectiveDate")
  private String effectiveDate = null;

  @SerializedName("expirationDate")
  private String expirationDate = null;

  @SerializedName("blockFlag")
  private Boolean blockFlag = null;

  public BlockPrivilege blockPrivTypeId(String blockPrivTypeId) {
    this.blockPrivTypeId = blockPrivTypeId;
    return this;
  }

   /**
   * Block or Privilege Type.  Please see <a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=BLPRI'>Block or Privilege codes</a>
   * @return blockPrivTypeId
  **/
  @ApiModelProperty(example = "null", required = true, value = "Block or Privilege Type.  Please see <a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=BLPRI'>Block or Privilege codes</a>")
  public String getBlockPrivTypeId() {
    return blockPrivTypeId;
  }

  public void setBlockPrivTypeId(String blockPrivTypeId) {
    this.blockPrivTypeId = blockPrivTypeId;
  }

  public BlockPrivilege effectiveDate(String effectiveDate) {
    this.effectiveDate = effectiveDate;
    return this;
  }

   /**
   * Effective date time in UTC such '2016-12-29T14:53:00-02:00'
   * @return effectiveDate
  **/
  @ApiModelProperty(example = "null", required = true, value = "Effective date time in UTC such '2016-12-29T14:53:00-02:00'")
  public String getEffectiveDate() {
    return effectiveDate;
  }

  public void setEffectiveDate(String effectiveDate) {
    this.effectiveDate = effectiveDate;
  }

  public BlockPrivilege expirationDate(String expirationDate) {
    this.expirationDate = expirationDate;
    return this;
  }

   /**
   * Effective date time in UTC such '2016-12-29T14:53:00-02:00'
   * @return expirationDate
  **/
  @ApiModelProperty(example = "null", required = true, value = "Effective date time in UTC such '2016-12-29T14:53:00-02:00'")
  public String getExpirationDate() {
    return expirationDate;
  }

  public void setExpirationDate(String expirationDate) {
    this.expirationDate = expirationDate;
  }

  public BlockPrivilege blockFlag(Boolean blockFlag) {
    this.blockFlag = blockFlag;
    return this;
  }

   /**
   * Get blockFlag
   * @return blockFlag
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getBlockFlag() {
    return blockFlag;
  }

  public void setBlockFlag(Boolean blockFlag) {
    this.blockFlag = blockFlag;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BlockPrivilege blockPrivilege = (BlockPrivilege) o;
    return Objects.equals(this.blockPrivTypeId, blockPrivilege.blockPrivTypeId) &&
        Objects.equals(this.effectiveDate, blockPrivilege.effectiveDate) &&
        Objects.equals(this.expirationDate, blockPrivilege.expirationDate) &&
        Objects.equals(this.blockFlag, blockPrivilege.blockFlag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(blockPrivTypeId, effectiveDate, expirationDate, blockFlag);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BlockPrivilege {\n");
    
    sb.append("    blockPrivTypeId: ").append(toIndentedString(blockPrivTypeId)).append("\n");
    sb.append("    effectiveDate: ").append(toIndentedString(effectiveDate)).append("\n");
    sb.append("    expirationDate: ").append(toIndentedString(expirationDate)).append("\n");
    sb.append("    blockFlag: ").append(toIndentedString(blockFlag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

