/**
 * Magic DMS RESTful Services
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.amway.integration.cis.v3.swagger;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Country
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-10T10:19:16.797+03:00")
public class Country   {
  @SerializedName("cntryCd")
  private String cntryCd = null;

  @SerializedName("cntryName")
  private String cntryName = null;

  @SerializedName("cntryDesc")
  private String cntryDesc = null;

  @SerializedName("amwayCntryCd")
  private String amwayCntryCd = null;

  @SerializedName("defaultCurrencyCd")
  private String defaultCurrencyCd = null;

  @SerializedName("defaultLanguageCd")
  private String defaultLanguageCd = null;

  @SerializedName("cntryGroupCd")
  private String cntryGroupCd = null;

  @SerializedName("defaultGeoCd")
  private String defaultGeoCd = null;

  @SerializedName("salesPlanAff")
  private Integer salesPlanAff = null;

  @SerializedName("dateFormat")
  private String dateFormat = null;

  @SerializedName("addrStreet")
  private String addrStreet = null;

  @SerializedName("addrLineTwo")
  private String addrLineTwo = null;

  @SerializedName("addrLineThree")
  private String addrLineThree = null;

  @SerializedName("cityName")
  private String cityName = null;

  @SerializedName("postalCd")
  private String postalCd = null;

  @SerializedName("stateCd")
  private String stateCd = null;

  @SerializedName("cntryAliasAboNum")
  private Long cntryAliasAboNum = null;

  @SerializedName("phoneCntryCd")
  private Integer phoneCntryCd = null;

  @SerializedName("cntryTimeZone")
  private String cntryTimeZone = null;

  public Country cntryCd(String cntryCd) {
    this.cntryCd = cntryCd;
    return this;
  }

   /**
   * Get cntryCd
   * @return cntryCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCntryCd() {
    return cntryCd;
  }

  public void setCntryCd(String cntryCd) {
    this.cntryCd = cntryCd;
  }

  public Country cntryName(String cntryName) {
    this.cntryName = cntryName;
    return this;
  }

   /**
   * Get cntryName
   * @return cntryName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCntryName() {
    return cntryName;
  }

  public void setCntryName(String cntryName) {
    this.cntryName = cntryName;
  }

  public Country cntryDesc(String cntryDesc) {
    this.cntryDesc = cntryDesc;
    return this;
  }

   /**
   * Get cntryDesc
   * @return cntryDesc
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCntryDesc() {
    return cntryDesc;
  }

  public void setCntryDesc(String cntryDesc) {
    this.cntryDesc = cntryDesc;
  }

  public Country amwayCntryCd(String amwayCntryCd) {
    this.amwayCntryCd = amwayCntryCd;
    return this;
  }

   /**
   * Get amwayCntryCd
   * @return amwayCntryCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAmwayCntryCd() {
    return amwayCntryCd;
  }

  public void setAmwayCntryCd(String amwayCntryCd) {
    this.amwayCntryCd = amwayCntryCd;
  }

  public Country defaultCurrencyCd(String defaultCurrencyCd) {
    this.defaultCurrencyCd = defaultCurrencyCd;
    return this;
  }

   /**
   * Get defaultCurrencyCd
   * @return defaultCurrencyCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDefaultCurrencyCd() {
    return defaultCurrencyCd;
  }

  public void setDefaultCurrencyCd(String defaultCurrencyCd) {
    this.defaultCurrencyCd = defaultCurrencyCd;
  }

  public Country defaultLanguageCd(String defaultLanguageCd) {
    this.defaultLanguageCd = defaultLanguageCd;
    return this;
  }

   /**
   * Get defaultLanguageCd
   * @return defaultLanguageCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDefaultLanguageCd() {
    return defaultLanguageCd;
  }

  public void setDefaultLanguageCd(String defaultLanguageCd) {
    this.defaultLanguageCd = defaultLanguageCd;
  }

  public Country cntryGroupCd(String cntryGroupCd) {
    this.cntryGroupCd = cntryGroupCd;
    return this;
  }

   /**
   * Get cntryGroupCd
   * @return cntryGroupCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCntryGroupCd() {
    return cntryGroupCd;
  }

  public void setCntryGroupCd(String cntryGroupCd) {
    this.cntryGroupCd = cntryGroupCd;
  }

  public Country defaultGeoCd(String defaultGeoCd) {
    this.defaultGeoCd = defaultGeoCd;
    return this;
  }

   /**
   * Get defaultGeoCd
   * @return defaultGeoCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDefaultGeoCd() {
    return defaultGeoCd;
  }

  public void setDefaultGeoCd(String defaultGeoCd) {
    this.defaultGeoCd = defaultGeoCd;
  }

  public Country salesPlanAff(Integer salesPlanAff) {
    this.salesPlanAff = salesPlanAff;
    return this;
  }

   /**
   * Get salesPlanAff
   * @return salesPlanAff
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getSalesPlanAff() {
    return salesPlanAff;
  }

  public void setSalesPlanAff(Integer salesPlanAff) {
    this.salesPlanAff = salesPlanAff;
  }

  public Country dateFormat(String dateFormat) {
    this.dateFormat = dateFormat;
    return this;
  }

   /**
   * Get dateFormat
   * @return dateFormat
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDateFormat() {
    return dateFormat;
  }

  public void setDateFormat(String dateFormat) {
    this.dateFormat = dateFormat;
  }

  public Country addrStreet(String addrStreet) {
    this.addrStreet = addrStreet;
    return this;
  }

   /**
   * Get addrStreet
   * @return addrStreet
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAddrStreet() {
    return addrStreet;
  }

  public void setAddrStreet(String addrStreet) {
    this.addrStreet = addrStreet;
  }

  public Country addrLineTwo(String addrLineTwo) {
    this.addrLineTwo = addrLineTwo;
    return this;
  }

   /**
   * Get addrLineTwo
   * @return addrLineTwo
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAddrLineTwo() {
    return addrLineTwo;
  }

  public void setAddrLineTwo(String addrLineTwo) {
    this.addrLineTwo = addrLineTwo;
  }

  public Country addrLineThree(String addrLineThree) {
    this.addrLineThree = addrLineThree;
    return this;
  }

   /**
   * Get addrLineThree
   * @return addrLineThree
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAddrLineThree() {
    return addrLineThree;
  }

  public void setAddrLineThree(String addrLineThree) {
    this.addrLineThree = addrLineThree;
  }

  public Country cityName(String cityName) {
    this.cityName = cityName;
    return this;
  }

   /**
   * Get cityName
   * @return cityName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCityName() {
    return cityName;
  }

  public void setCityName(String cityName) {
    this.cityName = cityName;
  }

  public Country postalCd(String postalCd) {
    this.postalCd = postalCd;
    return this;
  }

   /**
   * Get postalCd
   * @return postalCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPostalCd() {
    return postalCd;
  }

  public void setPostalCd(String postalCd) {
    this.postalCd = postalCd;
  }

  public Country stateCd(String stateCd) {
    this.stateCd = stateCd;
    return this;
  }

   /**
   * Get stateCd
   * @return stateCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStateCd() {
    return stateCd;
  }

  public void setStateCd(String stateCd) {
    this.stateCd = stateCd;
  }

  public Country cntryAliasAboNum(Long cntryAliasAboNum) {
    this.cntryAliasAboNum = cntryAliasAboNum;
    return this;
  }

   /**
   * Get cntryAliasAboNum
   * @return cntryAliasAboNum
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCntryAliasAboNum() {
    return cntryAliasAboNum;
  }

  public void setCntryAliasAboNum(Long cntryAliasAboNum) {
    this.cntryAliasAboNum = cntryAliasAboNum;
  }

  public Country phoneCntryCd(Integer phoneCntryCd) {
    this.phoneCntryCd = phoneCntryCd;
    return this;
  }

   /**
   * Get phoneCntryCd
   * @return phoneCntryCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getPhoneCntryCd() {
    return phoneCntryCd;
  }

  public void setPhoneCntryCd(Integer phoneCntryCd) {
    this.phoneCntryCd = phoneCntryCd;
  }

  public Country cntryTimeZone(String cntryTimeZone) {
    this.cntryTimeZone = cntryTimeZone;
    return this;
  }

   /**
   * Get cntryTimeZone
   * @return cntryTimeZone
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCntryTimeZone() {
    return cntryTimeZone;
  }

  public void setCntryTimeZone(String cntryTimeZone) {
    this.cntryTimeZone = cntryTimeZone;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Country country = (Country) o;
    return Objects.equals(this.cntryCd, country.cntryCd) &&
        Objects.equals(this.cntryName, country.cntryName) &&
        Objects.equals(this.cntryDesc, country.cntryDesc) &&
        Objects.equals(this.amwayCntryCd, country.amwayCntryCd) &&
        Objects.equals(this.defaultCurrencyCd, country.defaultCurrencyCd) &&
        Objects.equals(this.defaultLanguageCd, country.defaultLanguageCd) &&
        Objects.equals(this.cntryGroupCd, country.cntryGroupCd) &&
        Objects.equals(this.defaultGeoCd, country.defaultGeoCd) &&
        Objects.equals(this.salesPlanAff, country.salesPlanAff) &&
        Objects.equals(this.dateFormat, country.dateFormat) &&
        Objects.equals(this.addrStreet, country.addrStreet) &&
        Objects.equals(this.addrLineTwo, country.addrLineTwo) &&
        Objects.equals(this.addrLineThree, country.addrLineThree) &&
        Objects.equals(this.cityName, country.cityName) &&
        Objects.equals(this.postalCd, country.postalCd) &&
        Objects.equals(this.stateCd, country.stateCd) &&
        Objects.equals(this.cntryAliasAboNum, country.cntryAliasAboNum) &&
        Objects.equals(this.phoneCntryCd, country.phoneCntryCd) &&
        Objects.equals(this.cntryTimeZone, country.cntryTimeZone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cntryCd, cntryName, cntryDesc, amwayCntryCd, defaultCurrencyCd, defaultLanguageCd, cntryGroupCd, defaultGeoCd, salesPlanAff, dateFormat, addrStreet, addrLineTwo, addrLineThree, cityName, postalCd, stateCd, cntryAliasAboNum, phoneCntryCd, cntryTimeZone);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Country {\n");
    
    sb.append("    cntryCd: ").append(toIndentedString(cntryCd)).append("\n");
    sb.append("    cntryName: ").append(toIndentedString(cntryName)).append("\n");
    sb.append("    cntryDesc: ").append(toIndentedString(cntryDesc)).append("\n");
    sb.append("    amwayCntryCd: ").append(toIndentedString(amwayCntryCd)).append("\n");
    sb.append("    defaultCurrencyCd: ").append(toIndentedString(defaultCurrencyCd)).append("\n");
    sb.append("    defaultLanguageCd: ").append(toIndentedString(defaultLanguageCd)).append("\n");
    sb.append("    cntryGroupCd: ").append(toIndentedString(cntryGroupCd)).append("\n");
    sb.append("    defaultGeoCd: ").append(toIndentedString(defaultGeoCd)).append("\n");
    sb.append("    salesPlanAff: ").append(toIndentedString(salesPlanAff)).append("\n");
    sb.append("    dateFormat: ").append(toIndentedString(dateFormat)).append("\n");
    sb.append("    addrStreet: ").append(toIndentedString(addrStreet)).append("\n");
    sb.append("    addrLineTwo: ").append(toIndentedString(addrLineTwo)).append("\n");
    sb.append("    addrLineThree: ").append(toIndentedString(addrLineThree)).append("\n");
    sb.append("    cityName: ").append(toIndentedString(cityName)).append("\n");
    sb.append("    postalCd: ").append(toIndentedString(postalCd)).append("\n");
    sb.append("    stateCd: ").append(toIndentedString(stateCd)).append("\n");
    sb.append("    cntryAliasAboNum: ").append(toIndentedString(cntryAliasAboNum)).append("\n");
    sb.append("    phoneCntryCd: ").append(toIndentedString(phoneCntryCd)).append("\n");
    sb.append("    cntryTimeZone: ").append(toIndentedString(cntryTimeZone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

