/**
 * Magic DMS RESTful Services
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.amway.integration.cis.v3.swagger;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;


/**
 * LeadsProgramRequest
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-10T10:19:16.797+03:00")
public class LeadsProgramRequest   {
  @SerializedName("contractAcceptFlg")
  private Boolean contractAcceptFlg = null;

  @SerializedName("accountSubTypeCdList")
  private List<String> accountSubTypeCdList = new ArrayList<String>();

  public LeadsProgramRequest contractAcceptFlg(Boolean contractAcceptFlg) {
    this.contractAcceptFlg = contractAcceptFlg;
    return this;
  }

   /**
   * Get contractAcceptFlg
   * @return contractAcceptFlg
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getContractAcceptFlg() {
    return contractAcceptFlg;
  }

  public void setContractAcceptFlg(Boolean contractAcceptFlg) {
    this.contractAcceptFlg = contractAcceptFlg;
  }

  public LeadsProgramRequest accountSubTypeCdList(List<String> accountSubTypeCdList) {
    this.accountSubTypeCdList = accountSubTypeCdList;
    return this;
  }

  public LeadsProgramRequest addAccountSubTypeCdListItem(String accountSubTypeCdListItem) {
    this.accountSubTypeCdList.add(accountSubTypeCdListItem);
    return this;
  }

   /**
   * Account Sub-type codes. Please see this <a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=ACCST'>link</a> for valid codes
   * @return accountSubTypeCdList
  **/
  @ApiModelProperty(example = "null", required = true, value = "Account Sub-type codes. Please see this <a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=ACCST'>link</a> for valid codes")
  public List<String> getAccountSubTypeCdList() {
    return accountSubTypeCdList;
  }

  public void setAccountSubTypeCdList(List<String> accountSubTypeCdList) {
    this.accountSubTypeCdList = accountSubTypeCdList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LeadsProgramRequest leadsProgramRequest = (LeadsProgramRequest) o;
    return Objects.equals(this.contractAcceptFlg, leadsProgramRequest.contractAcceptFlg) &&
        Objects.equals(this.accountSubTypeCdList, leadsProgramRequest.accountSubTypeCdList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contractAcceptFlg, accountSubTypeCdList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LeadsProgramRequest {\n");
    
    sb.append("    contractAcceptFlg: ").append(toIndentedString(contractAcceptFlg)).append("\n");
    sb.append("    accountSubTypeCdList: ").append(toIndentedString(accountSubTypeCdList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

