/**
 * Magic DMS RESTful Services
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.amway.integration.cis.v3.swagger;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * MissingInfoDetail
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-10T10:19:16.797+03:00")
public class MissingInfoDetail   {
  @SerializedName("partyId")
  private Long partyId = null;

  @SerializedName("missingInfoId")
  private String missingInfoId = null;

  @SerializedName("isoCntryCd")
  private String isoCntryCd = null;

  @SerializedName("dueDate")
  private String dueDate = null;

  @SerializedName("receiveDate")
  private String receiveDate = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("receiveUser")
  private String receiveUser = null;

  public MissingInfoDetail partyId(Long partyId) {
    this.partyId = partyId;
    return this;
  }

   /**
   * Get partyId
   * @return partyId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getPartyId() {
    return partyId;
  }

  public void setPartyId(Long partyId) {
    this.partyId = partyId;
  }

  public MissingInfoDetail missingInfoId(String missingInfoId) {
    this.missingInfoId = missingInfoId;
    return this;
  }

   /**
   * <a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=MISIN'>Reference to Missing Info Object Id</a>
   * @return missingInfoId
  **/
  @ApiModelProperty(example = "null", required = true, value = "<a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=MISIN'>Reference to Missing Info Object Id</a>")
  public String getMissingInfoId() {
    return missingInfoId;
  }

  public void setMissingInfoId(String missingInfoId) {
    this.missingInfoId = missingInfoId;
  }

  public MissingInfoDetail isoCntryCd(String isoCntryCd) {
    this.isoCntryCd = isoCntryCd;
    return this;
  }

   /**
   * Get isoCntryCd
   * @return isoCntryCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIsoCntryCd() {
    return isoCntryCd;
  }

  public void setIsoCntryCd(String isoCntryCd) {
    this.isoCntryCd = isoCntryCd;
  }

  public MissingInfoDetail dueDate(String dueDate) {
    this.dueDate = dueDate;
    return this;
  }

   /**
   * Get dueDate
   * @return dueDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDueDate() {
    return dueDate;
  }

  public void setDueDate(String dueDate) {
    this.dueDate = dueDate;
  }

  public MissingInfoDetail receiveDate(String receiveDate) {
    this.receiveDate = receiveDate;
    return this;
  }

   /**
   * Get receiveDate
   * @return receiveDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getReceiveDate() {
    return receiveDate;
  }

  public void setReceiveDate(String receiveDate) {
    this.receiveDate = receiveDate;
  }

  public MissingInfoDetail status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public MissingInfoDetail receiveUser(String receiveUser) {
    this.receiveUser = receiveUser;
    return this;
  }

   /**
   * Get receiveUser
   * @return receiveUser
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getReceiveUser() {
    return receiveUser;
  }

  public void setReceiveUser(String receiveUser) {
    this.receiveUser = receiveUser;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MissingInfoDetail missingInfoDetail = (MissingInfoDetail) o;
    return Objects.equals(this.partyId, missingInfoDetail.partyId) &&
        Objects.equals(this.missingInfoId, missingInfoDetail.missingInfoId) &&
        Objects.equals(this.isoCntryCd, missingInfoDetail.isoCntryCd) &&
        Objects.equals(this.dueDate, missingInfoDetail.dueDate) &&
        Objects.equals(this.receiveDate, missingInfoDetail.receiveDate) &&
        Objects.equals(this.status, missingInfoDetail.status) &&
        Objects.equals(this.receiveUser, missingInfoDetail.receiveUser);
  }

  @Override
  public int hashCode() {
    return Objects.hash(partyId, missingInfoId, isoCntryCd, dueDate, receiveDate, status, receiveUser);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MissingInfoDetail {\n");
    
    sb.append("    partyId: ").append(toIndentedString(partyId)).append("\n");
    sb.append("    missingInfoId: ").append(toIndentedString(missingInfoId)).append("\n");
    sb.append("    isoCntryCd: ").append(toIndentedString(isoCntryCd)).append("\n");
    sb.append("    dueDate: ").append(toIndentedString(dueDate)).append("\n");
    sb.append("    receiveDate: ").append(toIndentedString(receiveDate)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    receiveUser: ").append(toIndentedString(receiveUser)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

