/**
 * Magic DMS RESTful Services
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.amway.integration.cis.v3.swagger;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;


/**
 * Party
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-10T10:19:16.797+03:00")
@JsonIgnoreProperties(ignoreUnknown=true)
public class Party   {
  @SerializedName("partyMst")
  private PartyMaster partyMst = null;

  @SerializedName("nameList")
  private List<PartyName> nameList = new ArrayList<PartyName>();

  @SerializedName("addressList")
  private List<Address> addressList = new ArrayList<Address>();

  @SerializedName("phoneList")
  private List<Phone> phoneList = new ArrayList<Phone>();

  @SerializedName("ecommList")
  private List<Ecomm> ecommList = new ArrayList<Ecomm>();

  @SerializedName("taxList")
  private List<Tax> taxList = new ArrayList<Tax>();

  @SerializedName("personalIdList")
  private List<PersonalId> personalIdList = new ArrayList<PersonalId>();

  @SerializedName("preferenceList")
  private List<Preference> preferenceList = new ArrayList<Preference>();

  @SerializedName("missingInfoList")
  private List<MissingInfoDetail> missingInfoList = new ArrayList<MissingInfoDetail>();

  @SerializedName("bankAccountDetailList")
  private List<BankAccount> bankAccountDetailList = new ArrayList<BankAccount>();

  public Party partyMst(PartyMaster partyMst) {
    this.partyMst = partyMst;
    return this;
  }

   /**
   * Get partyMst
   * @return partyMst
  **/
  @ApiModelProperty(example = "null", value = "")
  public PartyMaster getPartyMst() {
    return partyMst;
  }

  public void setPartyMst(PartyMaster partyMst) {
    this.partyMst = partyMst;
  }

  public Party nameList(List<PartyName> nameList) {
    this.nameList = nameList;
    return this;
  }

  public Party addNameListItem(PartyName nameListItem) {
    this.nameList.add(nameListItem);
    return this;
  }

   /**
   * Get nameList
   * @return nameList
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<PartyName> getNameList() {
    return nameList;
  }

  public void setNameList(List<PartyName> nameList) {
    this.nameList = nameList;
  }

  public Party addressList(List<Address> addressList) {
    this.addressList = addressList;
    return this;
  }

  public Party addAddressListItem(Address addressListItem) {
    this.addressList.add(addressListItem);
    return this;
  }

   /**
   * Get addressList
   * @return addressList
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Address> getAddressList() {
    return addressList;
  }

  public void setAddressList(List<Address> addressList) {
    this.addressList = addressList;
  }

  public Party phoneList(List<Phone> phoneList) {
    this.phoneList = phoneList;
    return this;
  }

  public Party addPhoneListItem(Phone phoneListItem) {
    this.phoneList.add(phoneListItem);
    return this;
  }

   /**
   * Get phoneList
   * @return phoneList
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Phone> getPhoneList() {
    return phoneList;
  }

  public void setPhoneList(List<Phone> phoneList) {
    this.phoneList = phoneList;
  }

  public Party ecommList(List<Ecomm> ecommList) {
    this.ecommList = ecommList;
    return this;
  }

  public Party addEcommListItem(Ecomm ecommListItem) {
    this.ecommList.add(ecommListItem);
    return this;
  }

   /**
   * Get ecommList
   * @return ecommList
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Ecomm> getEcommList() {
    return ecommList;
  }

  public void setEcommList(List<Ecomm> ecommList) {
    this.ecommList = ecommList;
  }

  public Party taxList(List<Tax> taxList) {
    this.taxList = taxList;
    return this;
  }

  public Party addTaxListItem(Tax taxListItem) {
    this.taxList.add(taxListItem);
    return this;
  }

   /**
   * Get taxList
   * @return taxList
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Tax> getTaxList() {
    return taxList;
  }

  public void setTaxList(List<Tax> taxList) {
    this.taxList = taxList;
  }

  public Party personalIdList(List<PersonalId> personalIdList) {
    this.personalIdList = personalIdList;
    return this;
  }

  public Party addPersonalIdListItem(PersonalId personalIdListItem) {
    this.personalIdList.add(personalIdListItem);
    return this;
  }

   /**
   * Get personalIdList
   * @return personalIdList
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<PersonalId> getPersonalIdList() {
    return personalIdList;
  }

  public void setPersonalIdList(List<PersonalId> personalIdList) {
    this.personalIdList = personalIdList;
  }

  public Party preferenceList(List<Preference> preferenceList) {
    this.preferenceList = preferenceList;
    return this;
  }

  public Party addPreferenceListItem(Preference preferenceListItem) {
    this.preferenceList.add(preferenceListItem);
    return this;
  }

   /**
   * Get preferenceList
   * @return preferenceList
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<Preference> getPreferenceList() {
    return preferenceList;
  }

  public void setPreferenceList(List<Preference> preferenceList) {
    this.preferenceList = preferenceList;
  }

  public Party missingInfoList(List<MissingInfoDetail> missingInfoList) {
    this.missingInfoList = missingInfoList;
    return this;
  }

  public Party addMissingInfoListItem(MissingInfoDetail missingInfoListItem) {
    this.missingInfoList.add(missingInfoListItem);
    return this;
  }

   /**
   * Get missingInfoList
   * @return missingInfoList
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<MissingInfoDetail> getMissingInfoList() {
    return missingInfoList;
  }

  public void setMissingInfoList(List<MissingInfoDetail> missingInfoList) {
    this.missingInfoList = missingInfoList;
  }

  public Party bankAccountDetailList(List<BankAccount> bankAccountDetailList) {
    this.bankAccountDetailList = bankAccountDetailList;
    return this;
  }

  public Party addBankAccountDetailListItem(BankAccount bankAccountDetailListItem) {
    this.bankAccountDetailList.add(bankAccountDetailListItem);
    return this;
  }

   /**
   * Get bankAccountDetailList
   * @return bankAccountDetailList
  **/
  @ApiModelProperty(example = "null", value = "")
  public List<BankAccount> getBankAccountDetailList() {
    return bankAccountDetailList;
  }

  public void setBankAccountDetailList(List<BankAccount> bankAccountDetailList) {
    this.bankAccountDetailList = bankAccountDetailList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Party party = (Party) o;
    return Objects.equals(this.partyMst, party.partyMst) &&
        Objects.equals(this.nameList, party.nameList) &&
        Objects.equals(this.addressList, party.addressList) &&
        Objects.equals(this.phoneList, party.phoneList) &&
        Objects.equals(this.ecommList, party.ecommList) &&
        Objects.equals(this.taxList, party.taxList) &&
        Objects.equals(this.personalIdList, party.personalIdList) &&
        Objects.equals(this.preferenceList, party.preferenceList) &&
        Objects.equals(this.missingInfoList, party.missingInfoList) &&
        Objects.equals(this.bankAccountDetailList, party.bankAccountDetailList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(partyMst, nameList, addressList, phoneList, ecommList, taxList, personalIdList, preferenceList, missingInfoList, bankAccountDetailList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Party {\n");
    
    sb.append("    partyMst: ").append(toIndentedString(partyMst)).append("\n");
    sb.append("    nameList: ").append(toIndentedString(nameList)).append("\n");
    sb.append("    addressList: ").append(toIndentedString(addressList)).append("\n");
    sb.append("    phoneList: ").append(toIndentedString(phoneList)).append("\n");
    sb.append("    ecommList: ").append(toIndentedString(ecommList)).append("\n");
    sb.append("    taxList: ").append(toIndentedString(taxList)).append("\n");
    sb.append("    personalIdList: ").append(toIndentedString(personalIdList)).append("\n");
    sb.append("    preferenceList: ").append(toIndentedString(preferenceList)).append("\n");
    sb.append("    missingInfoList: ").append(toIndentedString(missingInfoList)).append("\n");
    sb.append("    bankAccountDetailList: ").append(toIndentedString(bankAccountDetailList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

