/**
 * Magic DMS RESTful Services
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.amway.integration.cis.v3.swagger;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * PhoneRequest
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-10T10:19:16.797+03:00")
public class PhoneRequest   {
  @SerializedName("phone")
  private PhoneInput phone = null;

  @SerializedName("applyToAllLinkedAccountFlag")
  private Boolean applyToAllLinkedAccountFlag = null;

  public PhoneRequest phone(PhoneInput phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Phone Information
   * @return phone
  **/
  @ApiModelProperty(example = "null", required = true, value = "Phone Information")
  public PhoneInput getPhone() {
    return phone;
  }

  public void setPhone(PhoneInput phone) {
    this.phone = phone;
  }

  public PhoneRequest applyToAllLinkedAccountFlag(Boolean applyToAllLinkedAccountFlag) {
    this.applyToAllLinkedAccountFlag = applyToAllLinkedAccountFlag;
    return this;
  }

   /**
   * Apply changes to all linked accounts flag
   * @return applyToAllLinkedAccountFlag
  **/
  @ApiModelProperty(example = "null", required = true, value = "Apply changes to all linked accounts flag")
  public Boolean getApplyToAllLinkedAccountFlag() {
    return applyToAllLinkedAccountFlag;
  }

  public void setApplyToAllLinkedAccountFlag(Boolean applyToAllLinkedAccountFlag) {
    this.applyToAllLinkedAccountFlag = applyToAllLinkedAccountFlag;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PhoneRequest phoneRequest = (PhoneRequest) o;
    return Objects.equals(this.phone, phoneRequest.phone) &&
        Objects.equals(this.applyToAllLinkedAccountFlag, phoneRequest.applyToAllLinkedAccountFlag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(phone, applyToAllLinkedAccountFlag);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PhoneRequest {\n");
    
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    applyToAllLinkedAccountFlag: ").append(toIndentedString(applyToAllLinkedAccountFlag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

