/**
 * Magic DMS RESTful Services
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.amway.integration.cis.v3.swagger;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * PreferenceInput
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-10T10:19:16.797+03:00")
public class PreferenceInput   {
  @SerializedName("preferenceId")
  private String preferenceId = null;

  @SerializedName("isTrueFlg")
  private String isTrueFlg = null;

  @SerializedName("preferenceNote")
  private String preferenceNote = null;

  @SerializedName("preferenceListId")
  private String preferenceListId = null;

  public PreferenceInput preferenceId(String preferenceId) {
    this.preferenceId = preferenceId;
    return this;
  }

   /**
   * <a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=PRFID'>Reference to Preference Id types</a>
   * @return preferenceId
  **/
  @ApiModelProperty(example = "null", value = "<a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=PRFID'>Reference to Preference Id types</a>")
  public String getPreferenceId() {
    return preferenceId;
  }

  public void setPreferenceId(String preferenceId) {
    this.preferenceId = preferenceId;
  }

  public PreferenceInput isTrueFlg(String isTrueFlg) {
    this.isTrueFlg = isTrueFlg;
    return this;
  }

   /**
   * Get isTrueFlg
   * @return isTrueFlg
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIsTrueFlg() {
    return isTrueFlg;
  }

  public void setIsTrueFlg(String isTrueFlg) {
    this.isTrueFlg = isTrueFlg;
  }

  public PreferenceInput preferenceNote(String preferenceNote) {
    this.preferenceNote = preferenceNote;
    return this;
  }

   /**
   * Get preferenceNote
   * @return preferenceNote
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPreferenceNote() {
    return preferenceNote;
  }

  public void setPreferenceNote(String preferenceNote) {
    this.preferenceNote = preferenceNote;
  }

  public PreferenceInput preferenceListId(String preferenceListId) {
    this.preferenceListId = preferenceListId;
    return this;
  }

   /**
   * Get preferenceListId
   * @return preferenceListId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPreferenceListId() {
    return preferenceListId;
  }

  public void setPreferenceListId(String preferenceListId) {
    this.preferenceListId = preferenceListId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PreferenceInput preferenceInput = (PreferenceInput) o;
    return Objects.equals(this.preferenceId, preferenceInput.preferenceId) &&
        Objects.equals(this.isTrueFlg, preferenceInput.isTrueFlg) &&
        Objects.equals(this.preferenceNote, preferenceInput.preferenceNote) &&
        Objects.equals(this.preferenceListId, preferenceInput.preferenceListId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(preferenceId, isTrueFlg, preferenceNote, preferenceListId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PreferenceInput {\n");
    
    sb.append("    preferenceId: ").append(toIndentedString(preferenceId)).append("\n");
    sb.append("    isTrueFlg: ").append(toIndentedString(isTrueFlg)).append("\n");
    sb.append("    preferenceNote: ").append(toIndentedString(preferenceNote)).append("\n");
    sb.append("    preferenceListId: ").append(toIndentedString(preferenceListId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

