/**
 * Magic DMS RESTful Services
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.amway.integration.cis.v3.swagger;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * SearchPhone
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-10T10:19:16.797+03:00")
public class SearchPhone   {
  @SerializedName("phoneLocalNum")
  private String phoneLocalNum = null;

  @SerializedName("phoneCntryCd")
  private String phoneCntryCd = null;

  @SerializedName("phoneAreaCd")
  private String phoneAreaCd = null;

  @SerializedName("phoneExtNum")
  private String phoneExtNum = null;

  @SerializedName("statusCd")
  private String statusCd = null;

  public SearchPhone phoneLocalNum(String phoneLocalNum) {
    this.phoneLocalNum = phoneLocalNum;
    return this;
  }

   /**
   * Get phoneLocalNum
   * @return phoneLocalNum
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPhoneLocalNum() {
    return phoneLocalNum;
  }

  public void setPhoneLocalNum(String phoneLocalNum) {
    this.phoneLocalNum = phoneLocalNum;
  }

  public SearchPhone phoneCntryCd(String phoneCntryCd) {
    this.phoneCntryCd = phoneCntryCd;
    return this;
  }

   /**
   * Get phoneCntryCd
   * @return phoneCntryCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPhoneCntryCd() {
    return phoneCntryCd;
  }

  public void setPhoneCntryCd(String phoneCntryCd) {
    this.phoneCntryCd = phoneCntryCd;
  }

  public SearchPhone phoneAreaCd(String phoneAreaCd) {
    this.phoneAreaCd = phoneAreaCd;
    return this;
  }

   /**
   * Get phoneAreaCd
   * @return phoneAreaCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPhoneAreaCd() {
    return phoneAreaCd;
  }

  public void setPhoneAreaCd(String phoneAreaCd) {
    this.phoneAreaCd = phoneAreaCd;
  }

  public SearchPhone phoneExtNum(String phoneExtNum) {
    this.phoneExtNum = phoneExtNum;
    return this;
  }

   /**
   * Get phoneExtNum
   * @return phoneExtNum
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPhoneExtNum() {
    return phoneExtNum;
  }

  public void setPhoneExtNum(String phoneExtNum) {
    this.phoneExtNum = phoneExtNum;
  }

  public SearchPhone statusCd(String statusCd) {
    this.statusCd = statusCd;
    return this;
  }

   /**
   * Get statusCd
   * @return statusCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStatusCd() {
    return statusCd;
  }

  public void setStatusCd(String statusCd) {
    this.statusCd = statusCd;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchPhone searchPhone = (SearchPhone) o;
    return Objects.equals(this.phoneLocalNum, searchPhone.phoneLocalNum) &&
        Objects.equals(this.phoneCntryCd, searchPhone.phoneCntryCd) &&
        Objects.equals(this.phoneAreaCd, searchPhone.phoneAreaCd) &&
        Objects.equals(this.phoneExtNum, searchPhone.phoneExtNum) &&
        Objects.equals(this.statusCd, searchPhone.statusCd);
  }

  @Override
  public int hashCode() {
    return Objects.hash(phoneLocalNum, phoneCntryCd, phoneAreaCd, phoneExtNum, statusCd);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchPhone {\n");
    
    sb.append("    phoneLocalNum: ").append(toIndentedString(phoneLocalNum)).append("\n");
    sb.append("    phoneCntryCd: ").append(toIndentedString(phoneCntryCd)).append("\n");
    sb.append("    phoneAreaCd: ").append(toIndentedString(phoneAreaCd)).append("\n");
    sb.append("    phoneExtNum: ").append(toIndentedString(phoneExtNum)).append("\n");
    sb.append("    statusCd: ").append(toIndentedString(statusCd)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

