/**
 * Magic DMS RESTful Services
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.amway.integration.cis.v3.swagger;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * SubscriptionDelivery
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-10T10:19:16.797+03:00")
public class SubscriptionDelivery   {
  @SerializedName("deliveryTypeCd")
  private String deliveryTypeCd = null;

  @SerializedName("deliveryChoiceCd")
  private String deliveryChoiceCd = null;

  public SubscriptionDelivery deliveryTypeCd(String deliveryTypeCd) {
    this.deliveryTypeCd = deliveryTypeCd;
    return this;
  }

   /**
   * <a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=DLVRY'>Reference to Delivery Type codes</a>
   * @return deliveryTypeCd
  **/
  @ApiModelProperty(example = "null", required = true, value = "<a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=DLVRY'>Reference to Delivery Type codes</a>")
  public String getDeliveryTypeCd() {
    return deliveryTypeCd;
  }

  public void setDeliveryTypeCd(String deliveryTypeCd) {
    this.deliveryTypeCd = deliveryTypeCd;
  }

  public SubscriptionDelivery deliveryChoiceCd(String deliveryChoiceCd) {
    this.deliveryChoiceCd = deliveryChoiceCd;
    return this;
  }

   /**
   * Get deliveryChoiceCd
   * @return deliveryChoiceCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDeliveryChoiceCd() {
    return deliveryChoiceCd;
  }

  public void setDeliveryChoiceCd(String deliveryChoiceCd) {
    this.deliveryChoiceCd = deliveryChoiceCd;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionDelivery subscriptionDelivery = (SubscriptionDelivery) o;
    return Objects.equals(this.deliveryTypeCd, subscriptionDelivery.deliveryTypeCd) &&
        Objects.equals(this.deliveryChoiceCd, subscriptionDelivery.deliveryChoiceCd);
  }

  @Override
  public int hashCode() {
    return Objects.hash(deliveryTypeCd, deliveryChoiceCd);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionDelivery {\n");
    
    sb.append("    deliveryTypeCd: ").append(toIndentedString(deliveryTypeCd)).append("\n");
    sb.append("    deliveryChoiceCd: ").append(toIndentedString(deliveryChoiceCd)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

