/**
 * Magic DMS RESTful Services
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.amway.integration.cis.v3.swagger;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * Territory
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-10T10:19:16.797+03:00")
public class Territory   {
  @SerializedName("territryCd")
  private String territryCd = null;

  @SerializedName("territryNm")
  private String territryNm = null;

  @SerializedName("territryDesc")
  private String territryDesc = null;

  public Territory territryCd(String territryCd) {
    this.territryCd = territryCd;
    return this;
  }

   /**
   * Get territryCd
   * @return territryCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTerritryCd() {
    return territryCd;
  }

  public void setTerritryCd(String territryCd) {
    this.territryCd = territryCd;
  }

  public Territory territryNm(String territryNm) {
    this.territryNm = territryNm;
    return this;
  }

   /**
   * Get territryNm
   * @return territryNm
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTerritryNm() {
    return territryNm;
  }

  public void setTerritryNm(String territryNm) {
    this.territryNm = territryNm;
  }

  public Territory territryDesc(String territryDesc) {
    this.territryDesc = territryDesc;
    return this;
  }

   /**
   * Get territryDesc
   * @return territryDesc
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTerritryDesc() {
    return territryDesc;
  }

  public void setTerritryDesc(String territryDesc) {
    this.territryDesc = territryDesc;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Territory territory = (Territory) o;
    return Objects.equals(this.territryCd, territory.territryCd) &&
        Objects.equals(this.territryNm, territory.territryNm) &&
        Objects.equals(this.territryDesc, territory.territryDesc);
  }

  @Override
  public int hashCode() {
    return Objects.hash(territryCd, territryNm, territryDesc);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Territory {\n");
    
    sb.append("    territryCd: ").append(toIndentedString(territryCd)).append("\n");
    sb.append("    territryNm: ").append(toIndentedString(territryNm)).append("\n");
    sb.append("    territryDesc: ").append(toIndentedString(territryDesc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

