/**
 * Magic DMS RESTful Services
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.amway.integration.cis.v3.swagger;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * AccountBalanceRequest
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-10T10:19:16.797+03:00")
public class AccountBalanceRequest   {
  @SerializedName("balanceTypeCd")
  private String balanceTypeCd = null;

  @SerializedName("instrumentId")
  private String instrumentId = null;

  @SerializedName("currencyCd")
  private String currencyCd = null;

  @SerializedName("balanceAmount")
  private String balanceAmount = null;

  @SerializedName("txSourceCd")
  private String txSourceCd = null;

  @SerializedName("sourcRefNum")
  private String sourcRefNum = null;

  @SerializedName("txTypeCd")
  private String txTypeCd = null;

  @SerializedName("txIsoCntryCd")
  private String txIsoCntryCd = null;

  public AccountBalanceRequest balanceTypeCd(String balanceTypeCd) {
    this.balanceTypeCd = balanceTypeCd;
    return this;
  }

   /**
   * <a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=BALCD'>Reference to Account Balance Type codes</a>
   * @return balanceTypeCd
  **/
  @ApiModelProperty(example = "null", value = "<a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=BALCD'>Reference to Account Balance Type codes</a>")
  public String getBalanceTypeCd() {
    return balanceTypeCd;
  }

  public void setBalanceTypeCd(String balanceTypeCd) {
    this.balanceTypeCd = balanceTypeCd;
  }

  public AccountBalanceRequest instrumentId(String instrumentId) {
    this.instrumentId = instrumentId;
    return this;
  }

   /**
   * Get instrumentId
   * @return instrumentId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getInstrumentId() {
    return instrumentId;
  }

  public void setInstrumentId(String instrumentId) {
    this.instrumentId = instrumentId;
  }

  public AccountBalanceRequest currencyCd(String currencyCd) {
    this.currencyCd = currencyCd;
    return this;
  }

   /**
   * <a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=ISOCU'>Reference to Currency Codes</a>
   * @return currencyCd
  **/
  @ApiModelProperty(example = "null", value = "<a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=ISOCU'>Reference to Currency Codes</a>")
  public String getCurrencyCd() {
    return currencyCd;
  }

  public void setCurrencyCd(String currencyCd) {
    this.currencyCd = currencyCd;
  }

  public AccountBalanceRequest balanceAmount(String balanceAmount) {
    this.balanceAmount = balanceAmount;
    return this;
  }

   /**
   * Get balanceAmount
   * @return balanceAmount
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBalanceAmount() {
    return balanceAmount;
  }

  public void setBalanceAmount(String balanceAmount) {
    this.balanceAmount = balanceAmount;
  }

  public AccountBalanceRequest txSourceCd(String txSourceCd) {
    this.txSourceCd = txSourceCd;
    return this;
  }

   /**
   * <a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=TXSRC'>Reference to Transaction Source codes</a>
   * @return txSourceCd
  **/
  @ApiModelProperty(example = "null", value = "<a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=TXSRC'>Reference to Transaction Source codes</a>")
  public String getTxSourceCd() {
    return txSourceCd;
  }

  public void setTxSourceCd(String txSourceCd) {
    this.txSourceCd = txSourceCd;
  }

  public AccountBalanceRequest sourcRefNum(String sourcRefNum) {
    this.sourcRefNum = sourcRefNum;
    return this;
  }

   /**
   * Get sourcRefNum
   * @return sourcRefNum
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSourcRefNum() {
    return sourcRefNum;
  }

  public void setSourcRefNum(String sourcRefNum) {
    this.sourcRefNum = sourcRefNum;
  }

  public AccountBalanceRequest txTypeCd(String txTypeCd) {
    this.txTypeCd = txTypeCd;
    return this;
  }

   /**
   * <a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=TXTCD'>Reference to Transaction Type codes</a>
   * @return txTypeCd
  **/
  @ApiModelProperty(example = "null", value = "<a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=TXTCD'>Reference to Transaction Type codes</a>")
  public String getTxTypeCd() {
    return txTypeCd;
  }

  public void setTxTypeCd(String txTypeCd) {
    this.txTypeCd = txTypeCd;
  }

  public AccountBalanceRequest txIsoCntryCd(String txIsoCntryCd) {
    this.txIsoCntryCd = txIsoCntryCd;
    return this;
  }

   /**
   * Get txIsoCntryCd
   * @return txIsoCntryCd
  **/
  @ApiModelProperty(example = "null", required = true, value = "")
  public String getTxIsoCntryCd() {
    return txIsoCntryCd;
  }

  public void setTxIsoCntryCd(String txIsoCntryCd) {
    this.txIsoCntryCd = txIsoCntryCd;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountBalanceRequest accountBalanceRequest = (AccountBalanceRequest) o;
    return Objects.equals(this.balanceTypeCd, accountBalanceRequest.balanceTypeCd) &&
        Objects.equals(this.instrumentId, accountBalanceRequest.instrumentId) &&
        Objects.equals(this.currencyCd, accountBalanceRequest.currencyCd) &&
        Objects.equals(this.balanceAmount, accountBalanceRequest.balanceAmount) &&
        Objects.equals(this.txSourceCd, accountBalanceRequest.txSourceCd) &&
        Objects.equals(this.sourcRefNum, accountBalanceRequest.sourcRefNum) &&
        Objects.equals(this.txTypeCd, accountBalanceRequest.txTypeCd) &&
        Objects.equals(this.txIsoCntryCd, accountBalanceRequest.txIsoCntryCd);
  }

  @Override
  public int hashCode() {
    return Objects.hash(balanceTypeCd, instrumentId, currencyCd, balanceAmount, txSourceCd, sourcRefNum, txTypeCd, txIsoCntryCd);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountBalanceRequest {\n");
    
    sb.append("    balanceTypeCd: ").append(toIndentedString(balanceTypeCd)).append("\n");
    sb.append("    instrumentId: ").append(toIndentedString(instrumentId)).append("\n");
    sb.append("    currencyCd: ").append(toIndentedString(currencyCd)).append("\n");
    sb.append("    balanceAmount: ").append(toIndentedString(balanceAmount)).append("\n");
    sb.append("    txSourceCd: ").append(toIndentedString(txSourceCd)).append("\n");
    sb.append("    sourcRefNum: ").append(toIndentedString(sourcRefNum)).append("\n");
    sb.append("    txTypeCd: ").append(toIndentedString(txTypeCd)).append("\n");
    sb.append("    txIsoCntryCd: ").append(toIndentedString(txIsoCntryCd)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

