/**
 * Magic DMS RESTful Services
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.amway.integration.cis.v3.swagger;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;


/**
 * AccountSearchRequest
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-10T10:19:16.797+03:00")
public class AccountSearchRequest   {
  @SerializedName("isoCntryCd")
  private List<String> isoCntryCd = new ArrayList<String>();

  @SerializedName("lastName")
  private String lastName = null;

  @SerializedName("emailAddress")
  private String emailAddress = null;

  @SerializedName("postalCode")
  private String postalCode = null;

  @SerializedName("phoneInfo")
  private AccountSearchPhoneInfoRequest phoneInfo = null;

  public AccountSearchRequest isoCntryCd(List<String> isoCntryCd) {
    this.isoCntryCd = isoCntryCd;
    return this;
  }

  public AccountSearchRequest addIsoCntryCdItem(String isoCntryCdItem) {
    this.isoCntryCd.add(isoCntryCdItem);
    return this;
  }

   /**
   * <a href='http://ed/Domains/Details/16'>Reference to ISO Country Codes</a>
   * @return isoCntryCd
  **/
  @ApiModelProperty(example = "null", value = "<a href='http://ed/Domains/Details/16'>Reference to ISO Country Codes</a>")
  public List<String> getIsoCntryCd() {
    return isoCntryCd;
  }

  public void setIsoCntryCd(List<String> isoCntryCd) {
    this.isoCntryCd = isoCntryCd;
  }

  public AccountSearchRequest lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Family Name
   * @return lastName
  **/
  @ApiModelProperty(example = "null", required = true, value = "Family Name")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public AccountSearchRequest emailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
    return this;
  }

   /**
   * Email Address
   * @return emailAddress
  **/
  @ApiModelProperty(example = "null", required = true, value = "Email Address")
  public String getEmailAddress() {
    return emailAddress;
  }

  public void setEmailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
  }

  public AccountSearchRequest postalCode(String postalCode) {
    this.postalCode = postalCode;
    return this;
  }

   /**
   * Postal Code
   * @return postalCode
  **/
  @ApiModelProperty(example = "null", required = true, value = "Postal Code")
  public String getPostalCode() {
    return postalCode;
  }

  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }

  public AccountSearchRequest phoneInfo(AccountSearchPhoneInfoRequest phoneInfo) {
    this.phoneInfo = phoneInfo;
    return this;
  }

   /**
   * Phone Information
   * @return phoneInfo
  **/
  @ApiModelProperty(example = "null", required = true, value = "Phone Information")
  public AccountSearchPhoneInfoRequest getPhoneInfo() {
    return phoneInfo;
  }

  public void setPhoneInfo(AccountSearchPhoneInfoRequest phoneInfo) {
    this.phoneInfo = phoneInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountSearchRequest accountSearchRequest = (AccountSearchRequest) o;
    return Objects.equals(this.isoCntryCd, accountSearchRequest.isoCntryCd) &&
        Objects.equals(this.lastName, accountSearchRequest.lastName) &&
        Objects.equals(this.emailAddress, accountSearchRequest.emailAddress) &&
        Objects.equals(this.postalCode, accountSearchRequest.postalCode) &&
        Objects.equals(this.phoneInfo, accountSearchRequest.phoneInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isoCntryCd, lastName, emailAddress, postalCode, phoneInfo);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountSearchRequest {\n");
    
    sb.append("    isoCntryCd: ").append(toIndentedString(isoCntryCd)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    emailAddress: ").append(toIndentedString(emailAddress)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    phoneInfo: ").append(toIndentedString(phoneInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

