/**
 * Magic DMS RESTful Services
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.amway.integration.cis.v3.swagger;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * AccountMaster
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-10T10:19:16.797+03:00")
@JsonIgnoreProperties(ignoreUnknown=true)
public class AccountMaster   {
  @SerializedName("salesPlanAff")
  private String salesPlanAff = null;

  @SerializedName("accountTypeCd")
  private String accountTypeCd = null;

  @SerializedName("cntryCd")
  private String cntryCd = null;

  @SerializedName("languageCd")
  private String languageCd = null;

  @SerializedName("currencyCd")
  private String currencyCd = null;

  @SerializedName("lglEntityType")
  private String lglEntityType = null;

  @SerializedName("loaCd")
  private String loaCd = null;

  @SerializedName("statusCd")
  private String statusCd = null;

  @SerializedName("aboEntryDate")
  private String aboEntryDate = null;

  @SerializedName("accountName")
  private String accountName = null;

  @SerializedName("company")
  private String company = null;

  @SerializedName("includeExcludeFlg")
  private String includeExcludeFlg = null;

  @SerializedName("userPin")
  private String userPin = null;

  @SerializedName("blackListFlg")
  private String blackListFlg = null;

  @SerializedName("accountSubTypeCd")
  private String accountSubTypeCd = null;

  @SerializedName("busEntityNum")
  private String busEntityNum = null;

  @SerializedName("segmentCd")
  private String segmentCd = null;

  @SerializedName("regdSpnIboNo")
  private String regdSpnIboNo = null;

  @SerializedName("regdlntlSpnAffNo")
  private String regdlntlSpnAffNo = null;

  @SerializedName("regdlntlSpnIboNo")
  private String regdlntlSpnIboNo = null;

  @SerializedName("regdlntlPrmyBusflg")
  private String regdlntlPrmyBusflg = null;

  @SerializedName("userId")
  private String userId = null;

  @SerializedName("aboExpireDate")
  private String aboExpireDate = null;

  @SerializedName("accountCreditLimit")
  private String accountCreditLimit = null;

  @SerializedName("accountCreditStatusCd")
  private String accountCreditStatusCd = null;

  @SerializedName("accountMissingInfoFlg")
  private String accountMissingInfoFlg = null;

  @SerializedName("orderCreditLimit")
  private String orderCreditLimit = null;

  @SerializedName("aboNum")
  private String aboNum = null;

  @SerializedName("primaryPersonPartyId")
  private String primaryPersonPartyId = null;

  @SerializedName("lateRenewalEligibleFlg")
  private String lateRenewalEligibleFlg = null;

  @SerializedName("renewalFlag")
  private String renewalFlag = null;

  public AccountMaster salesPlanAff(String salesPlanAff) {
    this.salesPlanAff = salesPlanAff;
    return this;
  }

   /**
   * Get salesPlanAff
   * @return salesPlanAff
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSalesPlanAff() {
    return salesPlanAff;
  }

  public void setSalesPlanAff(String salesPlanAff) {
    this.salesPlanAff = salesPlanAff;
  }

  public AccountMaster accountTypeCd(String accountTypeCd) {
    this.accountTypeCd = accountTypeCd;
    return this;
  }

   /**
   * Get accountTypeCd
   * @return accountTypeCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAccountTypeCd() {
    return accountTypeCd;
  }

  public void setAccountTypeCd(String accountTypeCd) {
    this.accountTypeCd = accountTypeCd;
  }

  public AccountMaster cntryCd(String cntryCd) {
    this.cntryCd = cntryCd;
    return this;
  }

   /**
   * Get cntryCd
   * @return cntryCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCntryCd() {
    return cntryCd;
  }

  public void setCntryCd(String cntryCd) {
    this.cntryCd = cntryCd;
  }

  public AccountMaster languageCd(String languageCd) {
    this.languageCd = languageCd;
    return this;
  }

   /**
   * Get languageCd
   * @return languageCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLanguageCd() {
    return languageCd;
  }

  public void setLanguageCd(String languageCd) {
    this.languageCd = languageCd;
  }

  public AccountMaster currencyCd(String currencyCd) {
    this.currencyCd = currencyCd;
    return this;
  }

   /**
   * Get currencyCd
   * @return currencyCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCurrencyCd() {
    return currencyCd;
  }

  public void setCurrencyCd(String currencyCd) {
    this.currencyCd = currencyCd;
  }

  public AccountMaster lglEntityType(String lglEntityType) {
    this.lglEntityType = lglEntityType;
    return this;
  }

   /**
   * Get lglEntityType
   * @return lglEntityType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLglEntityType() {
    return lglEntityType;
  }

  public void setLglEntityType(String lglEntityType) {
    this.lglEntityType = lglEntityType;
  }

  public AccountMaster loaCd(String loaCd) {
    this.loaCd = loaCd;
    return this;
  }

   /**
   * Get loaCd
   * @return loaCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLoaCd() {
    return loaCd;
  }

  public void setLoaCd(String loaCd) {
    this.loaCd = loaCd;
  }

  public AccountMaster statusCd(String statusCd) {
    this.statusCd = statusCd;
    return this;
  }

   /**
   * Get statusCd
   * @return statusCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStatusCd() {
    return statusCd;
  }

  public void setStatusCd(String statusCd) {
    this.statusCd = statusCd;
  }

  public AccountMaster aboEntryDate(String aboEntryDate) {
    this.aboEntryDate = aboEntryDate;
    return this;
  }

   /**
   * Get aboEntryDate
   * @return aboEntryDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAboEntryDate() {
    return aboEntryDate;
  }

  public void setAboEntryDate(String aboEntryDate) {
    this.aboEntryDate = aboEntryDate;
  }

  public AccountMaster accountName(String accountName) {
    this.accountName = accountName;
    return this;
  }

   /**
   * Get accountName
   * @return accountName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAccountName() {
    return accountName;
  }

  public void setAccountName(String accountName) {
    this.accountName = accountName;
  }

  public AccountMaster company(String company) {
    this.company = company;
    return this;
  }

   /**
   * Get company
   * @return company
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCompany() {
    return company;
  }

  public void setCompany(String company) {
    this.company = company;
  }

  public AccountMaster includeExcludeFlg(String includeExcludeFlg) {
    this.includeExcludeFlg = includeExcludeFlg;
    return this;
  }

   /**
   * Get includeExcludeFlg
   * @return includeExcludeFlg
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getIncludeExcludeFlg() {
    return includeExcludeFlg;
  }

  public void setIncludeExcludeFlg(String includeExcludeFlg) {
    this.includeExcludeFlg = includeExcludeFlg;
  }

  public AccountMaster userPin(String userPin) {
    this.userPin = userPin;
    return this;
  }

   /**
   * Get userPin
   * @return userPin
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserPin() {
    return userPin;
  }

  public void setUserPin(String userPin) {
    this.userPin = userPin;
  }

  public AccountMaster blackListFlg(String blackListFlg) {
    this.blackListFlg = blackListFlg;
    return this;
  }

   /**
   * Get blackListFlg
   * @return blackListFlg
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBlackListFlg() {
    return blackListFlg;
  }

  public void setBlackListFlg(String blackListFlg) {
    this.blackListFlg = blackListFlg;
  }

  public AccountMaster accountSubTypeCd(String accountSubTypeCd) {
    this.accountSubTypeCd = accountSubTypeCd;
    return this;
  }

   /**
   * Get accountSubTypeCd
   * @return accountSubTypeCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAccountSubTypeCd() {
    return accountSubTypeCd;
  }

  public void setAccountSubTypeCd(String accountSubTypeCd) {
    this.accountSubTypeCd = accountSubTypeCd;
  }

  public AccountMaster busEntityNum(String busEntityNum) {
    this.busEntityNum = busEntityNum;
    return this;
  }

   /**
   * Get busEntityNum
   * @return busEntityNum
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBusEntityNum() {
    return busEntityNum;
  }

  public void setBusEntityNum(String busEntityNum) {
    this.busEntityNum = busEntityNum;
  }

  public AccountMaster segmentCd(String segmentCd) {
    this.segmentCd = segmentCd;
    return this;
  }

   /**
   * Get segmentCd
   * @return segmentCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSegmentCd() {
    return segmentCd;
  }

  public void setSegmentCd(String segmentCd) {
    this.segmentCd = segmentCd;
  }

  public AccountMaster regdSpnIboNo(String regdSpnIboNo) {
    this.regdSpnIboNo = regdSpnIboNo;
    return this;
  }

   /**
   * Get regdSpnIboNo
   * @return regdSpnIboNo
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRegdSpnIboNo() {
    return regdSpnIboNo;
  }

  public void setRegdSpnIboNo(String regdSpnIboNo) {
    this.regdSpnIboNo = regdSpnIboNo;
  }

  public AccountMaster regdlntlSpnAffNo(String regdlntlSpnAffNo) {
    this.regdlntlSpnAffNo = regdlntlSpnAffNo;
    return this;
  }

   /**
   * Get regdlntlSpnAffNo
   * @return regdlntlSpnAffNo
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRegdlntlSpnAffNo() {
    return regdlntlSpnAffNo;
  }

  public void setRegdlntlSpnAffNo(String regdlntlSpnAffNo) {
    this.regdlntlSpnAffNo = regdlntlSpnAffNo;
  }

  public AccountMaster regdlntlSpnIboNo(String regdlntlSpnIboNo) {
    this.regdlntlSpnIboNo = regdlntlSpnIboNo;
    return this;
  }

   /**
   * Get regdlntlSpnIboNo
   * @return regdlntlSpnIboNo
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRegdlntlSpnIboNo() {
    return regdlntlSpnIboNo;
  }

  public void setRegdlntlSpnIboNo(String regdlntlSpnIboNo) {
    this.regdlntlSpnIboNo = regdlntlSpnIboNo;
  }

  public AccountMaster regdlntlPrmyBusflg(String regdlntlPrmyBusflg) {
    this.regdlntlPrmyBusflg = regdlntlPrmyBusflg;
    return this;
  }

   /**
   * Get regdlntlPrmyBusflg
   * @return regdlntlPrmyBusflg
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRegdlntlPrmyBusflg() {
    return regdlntlPrmyBusflg;
  }

  public void setRegdlntlPrmyBusflg(String regdlntlPrmyBusflg) {
    this.regdlntlPrmyBusflg = regdlntlPrmyBusflg;
  }

  public AccountMaster userId(String userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserId() {
    return userId;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public AccountMaster aboExpireDate(String aboExpireDate) {
    this.aboExpireDate = aboExpireDate;
    return this;
  }

   /**
   * Get aboExpireDate
   * @return aboExpireDate
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAboExpireDate() {
    return aboExpireDate;
  }

  public void setAboExpireDate(String aboExpireDate) {
    this.aboExpireDate = aboExpireDate;
  }

  public AccountMaster accountCreditLimit(String accountCreditLimit) {
    this.accountCreditLimit = accountCreditLimit;
    return this;
  }

   /**
   * Get accountCreditLimit
   * @return accountCreditLimit
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAccountCreditLimit() {
    return accountCreditLimit;
  }

  public void setAccountCreditLimit(String accountCreditLimit) {
    this.accountCreditLimit = accountCreditLimit;
  }

  public AccountMaster accountCreditStatusCd(String accountCreditStatusCd) {
    this.accountCreditStatusCd = accountCreditStatusCd;
    return this;
  }

   /**
   * Get accountCreditStatusCd
   * @return accountCreditStatusCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAccountCreditStatusCd() {
    return accountCreditStatusCd;
  }

  public void setAccountCreditStatusCd(String accountCreditStatusCd) {
    this.accountCreditStatusCd = accountCreditStatusCd;
  }

  public AccountMaster accountMissingInfoFlg(String accountMissingInfoFlg) {
    this.accountMissingInfoFlg = accountMissingInfoFlg;
    return this;
  }

   /**
   * Get accountMissingInfoFlg
   * @return accountMissingInfoFlg
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAccountMissingInfoFlg() {
    return accountMissingInfoFlg;
  }

  public void setAccountMissingInfoFlg(String accountMissingInfoFlg) {
    this.accountMissingInfoFlg = accountMissingInfoFlg;
  }

  public AccountMaster orderCreditLimit(String orderCreditLimit) {
    this.orderCreditLimit = orderCreditLimit;
    return this;
  }

   /**
   * Get orderCreditLimit
   * @return orderCreditLimit
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getOrderCreditLimit() {
    return orderCreditLimit;
  }

  public void setOrderCreditLimit(String orderCreditLimit) {
    this.orderCreditLimit = orderCreditLimit;
  }

  public AccountMaster aboNum(String aboNum) {
    this.aboNum = aboNum;
    return this;
  }

   /**
   * Get aboNum
   * @return aboNum
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAboNum() {
    return aboNum;
  }

  public void setAboNum(String aboNum) {
    this.aboNum = aboNum;
  }

  public AccountMaster primaryPersonPartyId(String primaryPersonPartyId) {
    this.primaryPersonPartyId = primaryPersonPartyId;
    return this;
  }

   /**
   * Get primaryPersonPartyId
   * @return primaryPersonPartyId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPrimaryPersonPartyId() {
    return primaryPersonPartyId;
  }

  public void setPrimaryPersonPartyId(String primaryPersonPartyId) {
    this.primaryPersonPartyId = primaryPersonPartyId;
  }

  public AccountMaster lateRenewalEligibleFlg(String lateRenewalEligibleFlg) {
    this.lateRenewalEligibleFlg = lateRenewalEligibleFlg;
    return this;
  }

   /**
   * Get lateRenewalEligibleFlg
   * @return lateRenewalEligibleFlg
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLateRenewalEligibleFlg() {
    return lateRenewalEligibleFlg;
  }

  public void setLateRenewalEligibleFlg(String lateRenewalEligibleFlg) {
    this.lateRenewalEligibleFlg = lateRenewalEligibleFlg;
  }

  public AccountMaster renewalFlag(String renewalFlag) {
    this.renewalFlag = renewalFlag;
    return this;
  }

   /**
   * Get renewalFlag
   * @return renewalFlag
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getRenewalFlag() {
    return renewalFlag;
  }

  public void setRenewalFlag(String renewalFlag) {
    this.renewalFlag = renewalFlag;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountMaster accountMaster = (AccountMaster) o;
    return Objects.equals(this.salesPlanAff, accountMaster.salesPlanAff) &&
        Objects.equals(this.accountTypeCd, accountMaster.accountTypeCd) &&
        Objects.equals(this.cntryCd, accountMaster.cntryCd) &&
        Objects.equals(this.languageCd, accountMaster.languageCd) &&
        Objects.equals(this.currencyCd, accountMaster.currencyCd) &&
        Objects.equals(this.lglEntityType, accountMaster.lglEntityType) &&
        Objects.equals(this.loaCd, accountMaster.loaCd) &&
        Objects.equals(this.statusCd, accountMaster.statusCd) &&
        Objects.equals(this.aboEntryDate, accountMaster.aboEntryDate) &&
        Objects.equals(this.accountName, accountMaster.accountName) &&
        Objects.equals(this.company, accountMaster.company) &&
        Objects.equals(this.includeExcludeFlg, accountMaster.includeExcludeFlg) &&
        Objects.equals(this.userPin, accountMaster.userPin) &&
        Objects.equals(this.blackListFlg, accountMaster.blackListFlg) &&
        Objects.equals(this.accountSubTypeCd, accountMaster.accountSubTypeCd) &&
        Objects.equals(this.busEntityNum, accountMaster.busEntityNum) &&
        Objects.equals(this.segmentCd, accountMaster.segmentCd) &&
        Objects.equals(this.regdSpnIboNo, accountMaster.regdSpnIboNo) &&
        Objects.equals(this.regdlntlSpnAffNo, accountMaster.regdlntlSpnAffNo) &&
        Objects.equals(this.regdlntlSpnIboNo, accountMaster.regdlntlSpnIboNo) &&
        Objects.equals(this.regdlntlPrmyBusflg, accountMaster.regdlntlPrmyBusflg) &&
        Objects.equals(this.userId, accountMaster.userId) &&
        Objects.equals(this.aboExpireDate, accountMaster.aboExpireDate) &&
        Objects.equals(this.accountCreditLimit, accountMaster.accountCreditLimit) &&
        Objects.equals(this.accountCreditStatusCd, accountMaster.accountCreditStatusCd) &&
        Objects.equals(this.accountMissingInfoFlg, accountMaster.accountMissingInfoFlg) &&
        Objects.equals(this.orderCreditLimit, accountMaster.orderCreditLimit) &&
        Objects.equals(this.aboNum, accountMaster.aboNum) &&
        Objects.equals(this.primaryPersonPartyId, accountMaster.primaryPersonPartyId) &&
        Objects.equals(this.lateRenewalEligibleFlg, accountMaster.lateRenewalEligibleFlg) &&
        Objects.equals(this.renewalFlag, accountMaster.renewalFlag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(salesPlanAff, accountTypeCd, cntryCd, languageCd, currencyCd, lglEntityType, loaCd, statusCd, aboEntryDate, accountName, company, includeExcludeFlg, userPin, blackListFlg, accountSubTypeCd, busEntityNum, segmentCd, regdSpnIboNo, regdlntlSpnAffNo, regdlntlSpnIboNo, regdlntlPrmyBusflg, userId, aboExpireDate, accountCreditLimit, accountCreditStatusCd, accountMissingInfoFlg, orderCreditLimit, aboNum, primaryPersonPartyId, lateRenewalEligibleFlg, renewalFlag);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountMaster {\n");
    
    sb.append("    salesPlanAff: ").append(toIndentedString(salesPlanAff)).append("\n");
    sb.append("    accountTypeCd: ").append(toIndentedString(accountTypeCd)).append("\n");
    sb.append("    cntryCd: ").append(toIndentedString(cntryCd)).append("\n");
    sb.append("    languageCd: ").append(toIndentedString(languageCd)).append("\n");
    sb.append("    currencyCd: ").append(toIndentedString(currencyCd)).append("\n");
    sb.append("    lglEntityType: ").append(toIndentedString(lglEntityType)).append("\n");
    sb.append("    loaCd: ").append(toIndentedString(loaCd)).append("\n");
    sb.append("    statusCd: ").append(toIndentedString(statusCd)).append("\n");
    sb.append("    aboEntryDate: ").append(toIndentedString(aboEntryDate)).append("\n");
    sb.append("    accountName: ").append(toIndentedString(accountName)).append("\n");
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    includeExcludeFlg: ").append(toIndentedString(includeExcludeFlg)).append("\n");
    sb.append("    userPin: ").append(toIndentedString(userPin)).append("\n");
    sb.append("    blackListFlg: ").append(toIndentedString(blackListFlg)).append("\n");
    sb.append("    accountSubTypeCd: ").append(toIndentedString(accountSubTypeCd)).append("\n");
    sb.append("    busEntityNum: ").append(toIndentedString(busEntityNum)).append("\n");
    sb.append("    segmentCd: ").append(toIndentedString(segmentCd)).append("\n");
    sb.append("    regdSpnIboNo: ").append(toIndentedString(regdSpnIboNo)).append("\n");
    sb.append("    regdlntlSpnAffNo: ").append(toIndentedString(regdlntlSpnAffNo)).append("\n");
    sb.append("    regdlntlSpnIboNo: ").append(toIndentedString(regdlntlSpnIboNo)).append("\n");
    sb.append("    regdlntlPrmyBusflg: ").append(toIndentedString(regdlntlPrmyBusflg)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    aboExpireDate: ").append(toIndentedString(aboExpireDate)).append("\n");
    sb.append("    accountCreditLimit: ").append(toIndentedString(accountCreditLimit)).append("\n");
    sb.append("    accountCreditStatusCd: ").append(toIndentedString(accountCreditStatusCd)).append("\n");
    sb.append("    accountMissingInfoFlg: ").append(toIndentedString(accountMissingInfoFlg)).append("\n");
    sb.append("    orderCreditLimit: ").append(toIndentedString(orderCreditLimit)).append("\n");
    sb.append("    aboNum: ").append(toIndentedString(aboNum)).append("\n");
    sb.append("    primaryPersonPartyId: ").append(toIndentedString(primaryPersonPartyId)).append("\n");
    sb.append("    lateRenewalEligibleFlg: ").append(toIndentedString(lateRenewalEligibleFlg)).append("\n");
    sb.append("    renewalFlag: ").append(toIndentedString(renewalFlag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

