/**
 * Magic DMS RESTful Services
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.amway.integration.cis.v3.swagger;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * AccountUpdate
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-10T10:19:16.797+03:00")
public class AccountUpdate   {
  @SerializedName("languageCd")
  private String languageCd = null;

  @SerializedName("currencyCd")
  private String currencyCd = null;

  @SerializedName("loaCd")
  private String loaCd = null;

  @SerializedName("userPin")
  private String userPin = null;

  public AccountUpdate languageCd(String languageCd) {
    this.languageCd = languageCd;
    return this;
  }

   /**
   * Get languageCd
   * @return languageCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLanguageCd() {
    return languageCd;
  }

  public void setLanguageCd(String languageCd) {
    this.languageCd = languageCd;
  }

  public AccountUpdate currencyCd(String currencyCd) {
    this.currencyCd = currencyCd;
    return this;
  }

   /**
   * Get currencyCd
   * @return currencyCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCurrencyCd() {
    return currencyCd;
  }

  public void setCurrencyCd(String currencyCd) {
    this.currencyCd = currencyCd;
  }

  public AccountUpdate loaCd(String loaCd) {
    this.loaCd = loaCd;
    return this;
  }

   /**
   * Get loaCd
   * @return loaCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLoaCd() {
    return loaCd;
  }

  public void setLoaCd(String loaCd) {
    this.loaCd = loaCd;
  }

  public AccountUpdate userPin(String userPin) {
    this.userPin = userPin;
    return this;
  }

   /**
   * Get userPin
   * @return userPin
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getUserPin() {
    return userPin;
  }

  public void setUserPin(String userPin) {
    this.userPin = userPin;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountUpdate accountUpdate = (AccountUpdate) o;
    return Objects.equals(this.languageCd, accountUpdate.languageCd) &&
        Objects.equals(this.currencyCd, accountUpdate.currencyCd) &&
        Objects.equals(this.loaCd, accountUpdate.loaCd) &&
        Objects.equals(this.userPin, accountUpdate.userPin);
  }

  @Override
  public int hashCode() {
    return Objects.hash(languageCd, currencyCd, loaCd, userPin);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountUpdate {\n");
    
    sb.append("    languageCd: ").append(toIndentedString(languageCd)).append("\n");
    sb.append("    currencyCd: ").append(toIndentedString(currencyCd)).append("\n");
    sb.append("    loaCd: ").append(toIndentedString(loaCd)).append("\n");
    sb.append("    userPin: ").append(toIndentedString(userPin)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

