/**
 * Magic DMS RESTful Services
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.amway.integration.cis.v3.swagger;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * BusinessNatureChange
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-10T10:19:16.797+03:00")
public class BusinessNatureChange   {
  @SerializedName("accountSubTypeCd")
  private String accountSubTypeCd = null;

  @SerializedName("invoiceNum")
  private String invoiceNum = null;

  @SerializedName("reasonCd")
  private String reasonCd = null;

  public BusinessNatureChange accountSubTypeCd(String accountSubTypeCd) {
    this.accountSubTypeCd = accountSubTypeCd;
    return this;
  }

   /**
   * <a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=ACCST'>Reference to Account Sub Type Codes</a>
   * @return accountSubTypeCd
  **/
  @ApiModelProperty(example = "null", required = true, value = "<a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=ACCST'>Reference to Account Sub Type Codes</a>")
  public String getAccountSubTypeCd() {
    return accountSubTypeCd;
  }

  public void setAccountSubTypeCd(String accountSubTypeCd) {
    this.accountSubTypeCd = accountSubTypeCd;
  }

  public BusinessNatureChange invoiceNum(String invoiceNum) {
    this.invoiceNum = invoiceNum;
    return this;
  }

   /**
   * Get invoiceNum
   * @return invoiceNum
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getInvoiceNum() {
    return invoiceNum;
  }

  public void setInvoiceNum(String invoiceNum) {
    this.invoiceNum = invoiceNum;
  }

  public BusinessNatureChange reasonCd(String reasonCd) {
    this.reasonCd = reasonCd;
    return this;
  }

   /**
   * Get reasonCd
   * @return reasonCd
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getReasonCd() {
    return reasonCd;
  }

  public void setReasonCd(String reasonCd) {
    this.reasonCd = reasonCd;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BusinessNatureChange businessNatureChange = (BusinessNatureChange) o;
    return Objects.equals(this.accountSubTypeCd, businessNatureChange.accountSubTypeCd) &&
        Objects.equals(this.invoiceNum, businessNatureChange.invoiceNum) &&
        Objects.equals(this.reasonCd, businessNatureChange.reasonCd);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountSubTypeCd, invoiceNum, reasonCd);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BusinessNatureChange {\n");
    
    sb.append("    accountSubTypeCd: ").append(toIndentedString(accountSubTypeCd)).append("\n");
    sb.append("    invoiceNum: ").append(toIndentedString(invoiceNum)).append("\n");
    sb.append("    reasonCd: ").append(toIndentedString(reasonCd)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

