/**
 * Magic DMS RESTful Services
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.amway.integration.cis.v3.swagger;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;


/**
 * RegistrationSinglePartyRequest
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-10T10:19:16.797+03:00")
public class RegistrationSinglePartyRequest   {
  @SerializedName("clientIpAddress")
  private String clientIpAddress = null;

  @SerializedName("clientApplicationId")
  private String clientApplicationId = null;

  @SerializedName("clientChannelCd")
  private String clientChannelCd = null;

  @SerializedName("processTypeCd")
  private String processTypeCd = null;

  @SerializedName("aboNum")
  private Long aboNum = null;

  @SerializedName("cntryCd")
  private String cntryCd = null;

  @SerializedName("lglEnttyType")
  private String lglEnttyType = null;

  @SerializedName("accountSubTypeCd")
  private String accountSubTypeCd = null;

  @SerializedName("accountTypeCd")
  private String accountTypeCd = null;

  @SerializedName("contractAcceptFlg")
  private Boolean contractAcceptFlg = null;

  @SerializedName("authorizeEmail")
  private Boolean authorizeEmail = null;

  @SerializedName("languageCd")
  private String languageCd = null;

  @SerializedName("sponsor")
  private RegistrationSponsor sponsor = null;

  @SerializedName("formerAccount")
  private FormerAccountInput formerAccount = null;

  @SerializedName("primaryPartyIndex")
  private Integer primaryPartyIndex = null;

  @SerializedName("aboEntryDate")
  private String aboEntryDate = null;

  @SerializedName("party")
  private SimplePartyInput party = null;

  public RegistrationSinglePartyRequest clientIpAddress(String clientIpAddress) {
    this.clientIpAddress = clientIpAddress;
    return this;
  }

   /**
   * Browser's IP Address
   * @return clientIpAddress
  **/
  @ApiModelProperty(example = "null", required = true, value = "Browser's IP Address")
  public String getClientIpAddress() {
    return clientIpAddress;
  }

  public void setClientIpAddress(String clientIpAddress) {
    this.clientIpAddress = clientIpAddress;
  }

  public RegistrationSinglePartyRequest clientApplicationId(String clientApplicationId) {
    this.clientApplicationId = clientApplicationId;
    return this;
  }

   /**
   * Get clientApplicationId
   * @return clientApplicationId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getClientApplicationId() {
    return clientApplicationId;
  }

  public void setClientApplicationId(String clientApplicationId) {
    this.clientApplicationId = clientApplicationId;
  }

  public RegistrationSinglePartyRequest clientChannelCd(String clientChannelCd) {
    this.clientChannelCd = clientChannelCd;
    return this;
  }

   /**
   * Registration Source Channel. Please see this <a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=SRCHN'>link</a> for valid codes
   * @return clientChannelCd
  **/
  @ApiModelProperty(example = "null", required = true, value = "Registration Source Channel. Please see this <a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=SRCHN'>link</a> for valid codes")
  public String getClientChannelCd() {
    return clientChannelCd;
  }

  public void setClientChannelCd(String clientChannelCd) {
    this.clientChannelCd = clientChannelCd;
  }

  public RegistrationSinglePartyRequest processTypeCd(String processTypeCd) {
    this.processTypeCd = processTypeCd;
    return this;
  }

   /**
   * MAGIC DMS Process Type. Please see this <a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=PROTY'>link</a> for valid codes
   * @return processTypeCd
  **/
  @ApiModelProperty(example = "null", required = true, value = "MAGIC DMS Process Type. Please see this <a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=PROTY'>link</a> for valid codes")
  public String getProcessTypeCd() {
    return processTypeCd;
  }

  public void setProcessTypeCd(String processTypeCd) {
    this.processTypeCd = processTypeCd;
  }

  public RegistrationSinglePartyRequest aboNum(Long aboNum) {
    this.aboNum = aboNum;
    return this;
  }

   /**
   * ABO number
   * @return aboNum
  **/
  @ApiModelProperty(example = "null", required = true, value = "ABO number")
  public Long getAboNum() {
    return aboNum;
  }

  public void setAboNum(Long aboNum) {
    this.aboNum = aboNum;
  }

  public RegistrationSinglePartyRequest cntryCd(String cntryCd) {
    this.cntryCd = cntryCd;
    return this;
  }

   /**
   * ISO Country codes.
   * @return cntryCd
  **/
  @ApiModelProperty(example = "null", required = true, value = "ISO Country codes.")
  public String getCntryCd() {
    return cntryCd;
  }

  public void setCntryCd(String cntryCd) {
    this.cntryCd = cntryCd;
  }

  public RegistrationSinglePartyRequest lglEnttyType(String lglEnttyType) {
    this.lglEnttyType = lglEnttyType;
    return this;
  }

   /**
   * Legal Entity. Please see this <a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=LGETY'>link</a> for valid codes
   * @return lglEnttyType
  **/
  @ApiModelProperty(example = "null", required = true, value = "Legal Entity. Please see this <a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=LGETY'>link</a> for valid codes")
  public String getLglEnttyType() {
    return lglEnttyType;
  }

  public void setLglEnttyType(String lglEnttyType) {
    this.lglEnttyType = lglEnttyType;
  }

  public RegistrationSinglePartyRequest accountSubTypeCd(String accountSubTypeCd) {
    this.accountSubTypeCd = accountSubTypeCd;
    return this;
  }

   /**
   * Account Sub-type. Please see this <a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=ACCST'>link</a> for valid codes
   * @return accountSubTypeCd
  **/
  @ApiModelProperty(example = "null", required = true, value = "Account Sub-type. Please see this <a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=ACCST'>link</a> for valid codes")
  public String getAccountSubTypeCd() {
    return accountSubTypeCd;
  }

  public void setAccountSubTypeCd(String accountSubTypeCd) {
    this.accountSubTypeCd = accountSubTypeCd;
  }

  public RegistrationSinglePartyRequest accountTypeCd(String accountTypeCd) {
    this.accountTypeCd = accountTypeCd;
    return this;
  }

   /**
   * Account Type. Please see this <a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=ACTTY'>link</a> for valid codes
   * @return accountTypeCd
  **/
  @ApiModelProperty(example = "null", required = true, value = "Account Type. Please see this <a href='/DMS_Service_Web/DomainCodeLookUp.jsp?code=ACTTY'>link</a> for valid codes")
  public String getAccountTypeCd() {
    return accountTypeCd;
  }

  public void setAccountTypeCd(String accountTypeCd) {
    this.accountTypeCd = accountTypeCd;
  }

  public RegistrationSinglePartyRequest contractAcceptFlg(Boolean contractAcceptFlg) {
    this.contractAcceptFlg = contractAcceptFlg;
    return this;
  }

   /**
   * Get contractAcceptFlg
   * @return contractAcceptFlg
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getContractAcceptFlg() {
    return contractAcceptFlg;
  }

  public void setContractAcceptFlg(Boolean contractAcceptFlg) {
    this.contractAcceptFlg = contractAcceptFlg;
  }

  public RegistrationSinglePartyRequest authorizeEmail(Boolean authorizeEmail) {
    this.authorizeEmail = authorizeEmail;
    return this;
  }

   /**
   * Get authorizeEmail
   * @return authorizeEmail
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getAuthorizeEmail() {
    return authorizeEmail;
  }

  public void setAuthorizeEmail(Boolean authorizeEmail) {
    this.authorizeEmail = authorizeEmail;
  }

  public RegistrationSinglePartyRequest languageCd(String languageCd) {
    this.languageCd = languageCd;
    return this;
  }

   /**
   * Official ISO language code
   * @return languageCd
  **/
  @ApiModelProperty(example = "null", value = "Official ISO language code")
  public String getLanguageCd() {
    return languageCd;
  }

  public void setLanguageCd(String languageCd) {
    this.languageCd = languageCd;
  }

  public RegistrationSinglePartyRequest sponsor(RegistrationSponsor sponsor) {
    this.sponsor = sponsor;
    return this;
  }

   /**
   * Sponsor information
   * @return sponsor
  **/
  @ApiModelProperty(example = "null", required = true, value = "Sponsor information")
  public RegistrationSponsor getSponsor() {
    return sponsor;
  }

  public void setSponsor(RegistrationSponsor sponsor) {
    this.sponsor = sponsor;
  }

  public RegistrationSinglePartyRequest formerAccount(FormerAccountInput formerAccount) {
    this.formerAccount = formerAccount;
    return this;
  }

   /**
   * Former Amway Account
   * @return formerAccount
  **/
  @ApiModelProperty(example = "null", value = "Former Amway Account")
  public FormerAccountInput getFormerAccount() {
    return formerAccount;
  }

  public void setFormerAccount(FormerAccountInput formerAccount) {
    this.formerAccount = formerAccount;
  }

  public RegistrationSinglePartyRequest primaryPartyIndex(Integer primaryPartyIndex) {
    this.primaryPartyIndex = primaryPartyIndex;
    return this;
  }

   /**
   * Primary Party Index Number
   * @return primaryPartyIndex
  **/
  @ApiModelProperty(example = "null", value = "Primary Party Index Number")
  public Integer getPrimaryPartyIndex() {
    return primaryPartyIndex;
  }

  public void setPrimaryPartyIndex(Integer primaryPartyIndex) {
    this.primaryPartyIndex = primaryPartyIndex;
  }

  public RegistrationSinglePartyRequest aboEntryDate(String aboEntryDate) {
    this.aboEntryDate = aboEntryDate;
    return this;
  }

   /**
   * Account entry date
   * @return aboEntryDate
  **/
  @ApiModelProperty(example = "null", value = "Account entry date")
  public String getAboEntryDate() {
    return aboEntryDate;
  }

  public void setAboEntryDate(String aboEntryDate) {
    this.aboEntryDate = aboEntryDate;
  }

  public RegistrationSinglePartyRequest party(SimplePartyInput party) {
    this.party = party;
    return this;
  }

   /**
   * Party information
   * @return party
  **/
  @ApiModelProperty(example = "null", required = true, value = "Party information")
  public SimplePartyInput getParty() {
    return party;
  }

  public void setParty(SimplePartyInput party) {
    this.party = party;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegistrationSinglePartyRequest registrationSinglePartyRequest = (RegistrationSinglePartyRequest) o;
    return Objects.equals(this.clientIpAddress, registrationSinglePartyRequest.clientIpAddress) &&
        Objects.equals(this.clientApplicationId, registrationSinglePartyRequest.clientApplicationId) &&
        Objects.equals(this.clientChannelCd, registrationSinglePartyRequest.clientChannelCd) &&
        Objects.equals(this.processTypeCd, registrationSinglePartyRequest.processTypeCd) &&
        Objects.equals(this.aboNum, registrationSinglePartyRequest.aboNum) &&
        Objects.equals(this.cntryCd, registrationSinglePartyRequest.cntryCd) &&
        Objects.equals(this.lglEnttyType, registrationSinglePartyRequest.lglEnttyType) &&
        Objects.equals(this.accountSubTypeCd, registrationSinglePartyRequest.accountSubTypeCd) &&
        Objects.equals(this.accountTypeCd, registrationSinglePartyRequest.accountTypeCd) &&
        Objects.equals(this.contractAcceptFlg, registrationSinglePartyRequest.contractAcceptFlg) &&
        Objects.equals(this.authorizeEmail, registrationSinglePartyRequest.authorizeEmail) &&
        Objects.equals(this.languageCd, registrationSinglePartyRequest.languageCd) &&
        Objects.equals(this.sponsor, registrationSinglePartyRequest.sponsor) &&
        Objects.equals(this.formerAccount, registrationSinglePartyRequest.formerAccount) &&
        Objects.equals(this.primaryPartyIndex, registrationSinglePartyRequest.primaryPartyIndex) &&
        Objects.equals(this.aboEntryDate, registrationSinglePartyRequest.aboEntryDate) &&
        Objects.equals(this.party, registrationSinglePartyRequest.party);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientIpAddress, clientApplicationId, clientChannelCd, processTypeCd, aboNum, cntryCd, lglEnttyType, accountSubTypeCd, accountTypeCd, contractAcceptFlg, authorizeEmail, languageCd, sponsor, formerAccount, primaryPartyIndex, aboEntryDate, party);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegistrationSinglePartyRequest {\n");
    
    sb.append("    clientIpAddress: ").append(toIndentedString(clientIpAddress)).append("\n");
    sb.append("    clientApplicationId: ").append(toIndentedString(clientApplicationId)).append("\n");
    sb.append("    clientChannelCd: ").append(toIndentedString(clientChannelCd)).append("\n");
    sb.append("    processTypeCd: ").append(toIndentedString(processTypeCd)).append("\n");
    sb.append("    aboNum: ").append(toIndentedString(aboNum)).append("\n");
    sb.append("    cntryCd: ").append(toIndentedString(cntryCd)).append("\n");
    sb.append("    lglEnttyType: ").append(toIndentedString(lglEnttyType)).append("\n");
    sb.append("    accountSubTypeCd: ").append(toIndentedString(accountSubTypeCd)).append("\n");
    sb.append("    accountTypeCd: ").append(toIndentedString(accountTypeCd)).append("\n");
    sb.append("    contractAcceptFlg: ").append(toIndentedString(contractAcceptFlg)).append("\n");
    sb.append("    authorizeEmail: ").append(toIndentedString(authorizeEmail)).append("\n");
    sb.append("    languageCd: ").append(toIndentedString(languageCd)).append("\n");
    sb.append("    sponsor: ").append(toIndentedString(sponsor)).append("\n");
    sb.append("    formerAccount: ").append(toIndentedString(formerAccount)).append("\n");
    sb.append("    primaryPartyIndex: ").append(toIndentedString(primaryPartyIndex)).append("\n");
    sb.append("    aboEntryDate: ").append(toIndentedString(aboEntryDate)).append("\n");
    sb.append("    party: ").append(toIndentedString(party)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

