//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.25 at 07:43:28 PM IST 
//


package com.amway.integration.cis.los.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Created by aiu0256 on 5/22/15.
 * <p/>
 * <p/>
 * <p/>
 * Java class for aboLosAward complex type.
 * <p/>
 * <p/>
 * The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="aboLosAward">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Rank" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="QualifcationPeriod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "aboLosAward", propOrder = { "name", "code", "rank", "qualifcationPeriod" })
public class AboLosAward
{

	@XmlElement(name = "Name")
	protected String name;
	@XmlElement(name = "Code")
	protected String code;
	@XmlElement(name = "Rank")
	protected String rank;
	@XmlElement(name = "QualifcationPeriod")
	protected String qualifcationPeriod;

	/**
	 * Gets the value of the name property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Sets the value of the name property.
	 *
	 * @param value allowed object is {@link String }
	 */
	public void setName(final String value)
	{
		this.name = value;
	}

	/**
	 * Gets the value of the code property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getCode()
	{
		return code;
	}

	/**
	 * Sets the value of the code property.
	 *
	 * @param value allowed object is {@link String }
	 */
	public void setCode(final String value)
	{
		this.code = value;
	}

	/**
	 * Gets the value of the rank property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getRank()
	{
		return rank;
	}

	/**
	 * Sets the value of the rank property.
	 *
	 * @param value allowed object is {@link String }
	 */
	public void setRank(final String value)
	{
		this.rank = value;
	}

	/**
	 * Gets the value of the qualifcationPeriod property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getQualifcationPeriod()
	{
		return qualifcationPeriod;
	}

	/**
	 * Sets the value of the qualifcationPeriod property.
	 *
	 * @param value allowed object is {@link String }
	 */
	public void setQualifcationPeriod(final String value)
	{
		this.qualifcationPeriod = value;
	}

}
