//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.25 at 07:43:28 PM IST 
//


package com.amway.integration.cis.los.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Created by aiu0256 on 5/22/15.
 * <p/>
 * <p/>
 * <p/>
 * Java class for bonusVolume complex type.
 * <p/>
 * <p/>
 * The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="bonusVolume">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PV" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bonusVolume", propOrder = { "name", "code", "pv", "bv", "country", "currency" })
public class BonusVolume
{

	@XmlElement(name = "Name")
	protected String name;
	@XmlElement(name = "Code")
	protected String code;
	@XmlElement(name = "PV")
	protected Double pv;
	@XmlElement(name = "BV")
	protected Double bv;
	@XmlElement(name = "Country")
	protected String country;
	@XmlElement(name = "Currency")
	protected String currency;

	/**
	 * Gets the value of the name property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getName()
	{
		return name;
	}

	/**
	 * Sets the value of the name property.
	 *
	 * @param value allowed object is {@link String }
	 */
	public void setName(final String value)
	{
		this.name = value;
	}

	/**
	 * Gets the value of the code property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getCode()
	{
		return code;
	}

	/**
	 * Sets the value of the code property.
	 *
	 * @param value allowed object is {@link String }
	 */
	public void setCode(final String value)
	{
		this.code = value;
	}

	/**
	 * Gets the value of the pv property.
	 *
	 * @return possible object is {@link Double }
	 */
	public Double getPV()
	{
		return pv;
	}

	/**
	 * Sets the value of the pv property.
	 *
	 * @param value allowed object is {@link Double }
	 */
	public void setPV(final Double value)
	{
		this.pv = value;
	}

	/**
	 * Gets the value of the country property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getCountry()
	{
		return country;
	}

	/**
	 * Sets the value of the country property.
	 *
	 * @param value allowed object is {@link String }
	 */
	public void setCountry(final String value)
	{
		this.country = value;
	}

	/**
	 * Gets the value of the currency property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getCurrency()
	{
		return currency;
	}

	/**
	 * Sets the value of the currency property.
	 *
	 * @param value allowed object is {@link String }
	 */
	public void setCurrency(final String value)
	{
		this.currency = value;
	}

	/**
	 * @return bv
	 */
	public Double getBV()
	{
		return bv;
	}

	/**
	 * @param value
	 */
	public void setBV(final Double value)
	{
		this.bv = value;
	}

}
