//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.25 at 07:43:28 PM IST 
//


package com.amway.integration.cis.los.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Created by aiu0256 on 5/22/15.
 * <p/>
 * <p/>
 * <p/>
 * Java class for countryOrderCount complex type.
 * <p/>
 * <p/>
 * The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="countryOrderCount">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PersonalOrderCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="SponsoredCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="GroupABOCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="GroupOrderCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="NewGroupABOCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "countryOrderCount", propOrder = { "country", "currency", "personalOrderCount", "sponsoredCount", "groupABOCount",
		"groupOrderCount", "newGroupABOCount" })
public class CountryOrderCount
{

	@XmlElement(name = "Country")
	protected String country;
	@XmlElement(name = "Currency")
	protected String currency;
	@XmlElement(name = "PersonalOrderCount")
	protected int personalOrderCount;
	@XmlElement(name = "SponsoredCount")
	protected int sponsoredCount;
	@XmlElement(name = "GroupABOCount")
	protected int groupABOCount;
	@XmlElement(name = "GroupOrderCount")
	protected int groupOrderCount;
	@XmlElement(name = "NewGroupABOCount")
	protected int newGroupABOCount;

	/**
	 * Gets the value of the country property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getCountry()
	{
		return country;
	}

	/**
	 * Sets the value of the country property.
	 *
	 * @param value allowed object is {@link String }
	 */
	public void setCountry(final String value)
	{
		this.country = value;
	}

	/**
	 * Gets the value of the currency property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getCurrency()
	{
		return currency;
	}

	/**
	 * Sets the value of the currency property.
	 *
	 * @param value allowed object is {@link String }
	 */
	public void setCurrency(final String value)
	{
		this.currency = value;
	}

	/**
	 * Gets the value of the personalOrderCount property.
	 */
	public int getPersonalOrderCount()
	{
		return personalOrderCount;
	}

	/**
	 * Sets the value of the personalOrderCount property.
	 */
	public void setPersonalOrderCount(final int value)
	{
		this.personalOrderCount = value;
	}

	/**
	 * Gets the value of the sponsoredCount property.
	 */
	public int getSponsoredCount()
	{
		return sponsoredCount;
	}

	/**
	 * Sets the value of the sponsoredCount property.
	 */
	public void setSponsoredCount(final int value)
	{
		this.sponsoredCount = value;
	}

	/**
	 * Gets the value of the groupABOCount property.
	 */
	public int getGroupABOCount()
	{
		return groupABOCount;
	}

	/**
	 * Sets the value of the groupABOCount property.
	 */
	public void setGroupABOCount(final int value)
	{
		this.groupABOCount = value;
	}

	/**
	 * Gets the value of the groupOrderCount property.
	 */
	public int getGroupOrderCount()
	{
		return groupOrderCount;
	}

	/**
	 * Sets the value of the groupOrderCount property.
	 */
	public void setGroupOrderCount(final int value)
	{
		this.groupOrderCount = value;
	}

	/**
	 * Gets the value of the newGroupABOCount property.
	 */
	public int getNewGroupABOCount()
	{
		return newGroupABOCount;
	}

	/**
	 * Sets the value of the newGroupABOCount property.
	 */
	public void setNewGroupABOCount(final int value)
	{
		this.newGroupABOCount = value;
	}

}
