package com.alticor.ebsui.service;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated source version: 2.2
 */
@WebServiceClient(name = "LosSponsorValidationServiceService", targetNamespace = "http://service.ebsui.alticor.com", wsdlLocation = "http://magic-gamma:9092/EBS_UI_Service/services/LosSponsorValidationService/wsdl/LosSponsorValidationService.wsdl")
public class LosSponsorValidationServiceService extends Service
{

	private final static URL LOSSPONSORVALIDATIONSERVICESERVICE_WSDL_LOCATION;
	private final static WebServiceException LOSSPONSORVALIDATIONSERVICESERVICE_EXCEPTION;
	private final static QName LOSSPONSORVALIDATIONSERVICESERVICE_QNAME = new QName("http://service.ebsui.alticor.com",
			"LosSponsorValidationServiceService");

	static
	{
		URL url = null;
		WebServiceException e = null;
		try
		{
			url = new URL(
					"http://magic-gamma:9092/EBS_UI_Service/services/LosSponsorValidationService/wsdl/LosSponsorValidationService.wsdl");
		}
		catch (final MalformedURLException ex)
		{
			e = new WebServiceException(ex);
		}
		LOSSPONSORVALIDATIONSERVICESERVICE_WSDL_LOCATION = url;
		LOSSPONSORVALIDATIONSERVICESERVICE_EXCEPTION = e;
	}

	/**
	 * LosSponsorValidationServiceService
	 */
	public LosSponsorValidationServiceService()
	{
		super(__getWsdlLocation(), LOSSPONSORVALIDATIONSERVICESERVICE_QNAME);
	}

	/**
	 * LosSponsorValidationServiceService
	 *
	 * @param features
	 */
	public LosSponsorValidationServiceService(final WebServiceFeature... features)
	{
		super(__getWsdlLocation(), LOSSPONSORVALIDATIONSERVICESERVICE_QNAME, features);
	}

	/**
	 * LosSponsorValidationServiceService
	 *
	 * @param wsdlLocation
	 */
	public LosSponsorValidationServiceService(final URL wsdlLocation)
	{
		super(wsdlLocation, LOSSPONSORVALIDATIONSERVICESERVICE_QNAME);
	}

	/**
	 * LosSponsorValidationServiceService
	 *
	 * @param wsdlLocation
	 * @param features
	 */
	public LosSponsorValidationServiceService(final URL wsdlLocation, final WebServiceFeature... features)
	{
		super(wsdlLocation, LOSSPONSORVALIDATIONSERVICESERVICE_QNAME, features);
	}

	/**
	 * LosSponsorValidationServiceService
	 *
	 * @param wsdlLocation
	 * @param serviceName
	 */
	public LosSponsorValidationServiceService(final URL wsdlLocation, final QName serviceName)
	{
		super(wsdlLocation, serviceName);
	}

	/**
	 * LosSponsorValidationServiceService
	 *
	 * @param wsdlLocation
	 * @param serviceName
	 * @param features
	 */
	public LosSponsorValidationServiceService(final URL wsdlLocation, final QName serviceName, final WebServiceFeature... features)
	{
		super(wsdlLocation, serviceName, features);
	}

	/**
	 * @return returns LosSponsorValidationService
	 */
	@WebEndpoint(name = "LosSponsorValidationService")
	public LosSponsorValidationService getLosSponsorValidationService()
	{
		return super.getPort(new QName("http://service.ebsui.alticor.com", "LosSponsorValidationService"),
				LosSponsorValidationService.class);
	}

	/**
	 * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in
	 *                 the <code>features</code> parameter will have their default values.
	 * @return returns LosSponsorValidationService
	 */
	@WebEndpoint(name = "LosSponsorValidationService")
	public LosSponsorValidationService getLosSponsorValidationService(final WebServiceFeature... features)
	{
		return super.getPort(new QName("http://service.ebsui.alticor.com", "LosSponsorValidationService"),
				LosSponsorValidationService.class, features);
	}

	private static URL __getWsdlLocation()
	{
		if (LOSSPONSORVALIDATIONSERVICESERVICE_EXCEPTION != null)
		{
			throw LOSSPONSORVALIDATIONSERVICESERVICE_EXCEPTION;
		}
		return LOSSPONSORVALIDATIONSERVICESERVICE_WSDL_LOCATION;
	}

}
