package com.alticor.ebsui.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.amway.glos.dataobject.LosSponsorValidation;
import com.amway.glos.dataobject.LosSponsorValidationResults;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 */
@WebService(name = "LosSponsorValidationService", targetNamespace = "http://service.ebsui.alticor.com")
@XmlSeeAlso({ com.alticor.ebsui.service.ObjectFactory.class, com.amway.glos.dataobject.ObjectFactory.class })
public interface LosSponsorValidationService
{


	/**
	 * @param losSponVldnData
	 * @return returns com.amway.glos.dataobject.LosSponsorValidationResults
	 */
	@WebMethod(action = "validateSponsor")
	@WebResult(name = "validateSponsorReturn", targetNamespace = "")
	@RequestWrapper(localName = "validateSponsor", targetNamespace = "http://service.ebsui.alticor.com", className = "com.alticor.ebsui.service.ValidateSponsor")
	@ResponseWrapper(localName = "validateSponsorResponse", targetNamespace = "http://service.ebsui.alticor.com", className = "com.alticor.ebsui.service.ValidateSponsorResponse")
	public LosSponsorValidationResults validateSponsor(
			@WebParam(name = "losSponVldnData", targetNamespace = "") LosSponsorValidation losSponVldnData);

}
