//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.25 at 07:43:28 PM IST 
//


package com.amway.integration.cis.los.pojo;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Created by aiu0256 on 5/22/15.
 * <p/>
 * <p/>
 * <p/>
 * Java class for aboLosBonusPeriodStatistic complex type.
 * <p/>
 * <p/>
 * The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="aboLosBonusPeriodStatistic">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BonusPeriod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Sponsor" type="{}abo" minOccurs="0"/>
 *         &lt;element name="PlatinumSponsor" type="{}abo" minOccurs="0"/>
 *         &lt;element name="Volumes" type="{}bonusVolume" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CurrentPersonalPercentage" type="{}percentage" minOccurs="0"/>
 *         &lt;element name="CurrentLeadershipPercentage" type="{}percentage" minOccurs="0"/>
 *         &lt;element name="NextGroupPercentage" type="{}percentageAndVolume" minOccurs="0"/>
 *         &lt;element name="QualifiedLegs" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="InternationalQualifiedLegs" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="FosterQualifiedLegs" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "aboLosBonusPeriodStatistic", propOrder = { "bonusPeriod", "businessNatureCode", "status", "sponsor",
		"platinumSponsor", "volumes", "currentPersonalPercentage", "currentLeadershipPercentage", "nextGroupPercentage",
		"qualifiedLegs", "internationalQualifiedLegs", "fosterQualifiedLegs", "internationalSponsorABO", "inMarketQualifiedLegs" })
public class AboLosBonusPeriodStatistic
{

	@XmlElement(name = "BonusPeriod")
	protected String bonusPeriod;
	@XmlElement(name = "BusinessNatureCode")
	protected String businessNatureCode;
	@XmlElement(name = "Status")
	protected String status;
	@XmlElement(name = "Sponsor")
	protected Abo sponsor;
	@XmlElement(name = "PlatinumSponsor")
	protected Abo platinumSponsor;
	@XmlElement(name = "InternationalSponsorABO")
	protected Abo internationalSponsorABO;
	@XmlElement(name = "Volumes")
	protected List<BonusVolume> volumes;
	@XmlElement(name = "CurrentPersonalPercentage")
	protected Percentage currentPersonalPercentage;
	@XmlElement(name = "CurrentLeadershipPercentage")
	protected Percentage currentLeadershipPercentage;
	@XmlElement(name = "NextGroupPercentage")
	protected PercentageAndVolume nextGroupPercentage;
	@XmlElement(name = "QualifiedLegs")
	protected int qualifiedLegs;
	@XmlElement(name = "InternationalQualifiedLegs")
	protected int internationalQualifiedLegs;
	@XmlElement(name = "FosterQualifiedLegs")
	protected int fosterQualifiedLegs;
	@XmlElement(name = "InMarketQualifiedLegs")
	protected int inMarketQualifiedLegs;

	/**
	 * Gets the value of the bonusPeriod property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getBonusPeriod()
	{
		return bonusPeriod;
	}

	/**
	 * Sets the value of the bonusPeriod property.
	 *
	 * @param value allowed object is {@link String }
	 */
	public void setBonusPeriod(final String value)
	{
		this.bonusPeriod = value;
	}

	/**
	 * Gets the value of the status property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getStatus()
	{
		return status;
	}

	/**
	 * Sets the value of the status property.
	 *
	 * @param value allowed object is {@link String }
	 */
	public void setStatus(final String value)
	{
		this.status = value;
	}

	/**
	 * Gets the value of the sponsor property.
	 *
	 * @return possible object is {@link Abo }
	 */
	public Abo getSponsor()
	{
		return sponsor;
	}

	/**
	 * Sets the value of the sponsor property.
	 *
	 * @param value allowed object is {@link Abo }
	 */
	public void setSponsor(final Abo value)
	{
		this.sponsor = value;
	}

	/**
	 * Gets the value of the platinumSponsor property.
	 *
	 * @return possible object is {@link Abo }
	 */
	public Abo getPlatinumSponsor()
	{
		return platinumSponsor;
	}

	/**
	 * Sets the value of the platinumSponsor property.
	 *
	 * @param value allowed object is {@link Abo }
	 */
	public void setPlatinumSponsor(final Abo value)
	{
		this.platinumSponsor = value;
	}

	/**
	 * Gets the value of the volumes property.
	 * <p/>
	 * <p/>
	 * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
	 * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
	 * the volumes property.
	 * <p/>
	 * <p/>
	 * For example, to add a new item, do as follows:
	 * <p/>
	 * <pre>
	 * getVolumes().add(newItem);
	 * </pre>
	 * <p/>
	 * <p/>
	 * <p/>
	 * Objects of the following type(s) are allowed in the list {@link BonusVolume }
	 */
	public List<BonusVolume> getVolumes()
	{
		if (volumes == null)
		{
			volumes = new ArrayList<BonusVolume>();
		}
		return this.volumes;
	}

	/**
	 * Gets the value of the currentPersonalPercentage property.
	 *
	 * @return possible object is {@link Percentage }
	 */
	public Percentage getCurrentPersonalPercentage()
	{
		return currentPersonalPercentage;
	}

	/**
	 * Sets the value of the currentPersonalPercentage property.
	 *
	 * @param value allowed object is {@link Percentage }
	 */
	public void setCurrentPersonalPercentage(final Percentage value)
	{
		this.currentPersonalPercentage = value;
	}

	/**
	 * Gets the value of the currentLeadershipPercentage property.
	 *
	 * @return possible object is {@link Percentage }
	 */
	public Percentage getCurrentLeadershipPercentage()
	{
		return currentLeadershipPercentage;
	}

	/**
	 * Sets the value of the currentLeadershipPercentage property.
	 *
	 * @param value allowed object is {@link Percentage }
	 */
	public void setCurrentLeadershipPercentage(final Percentage value)
	{
		this.currentLeadershipPercentage = value;
	}

	/**
	 * Gets the value of the nextGroupPercentage property.
	 *
	 * @return possible object is {@link PercentageAndVolume }
	 */
	public PercentageAndVolume getNextGroupPercentage()
	{
		return nextGroupPercentage;
	}

	/**
	 * Sets the value of the nextGroupPercentage property.
	 *
	 * @param value allowed object is {@link PercentageAndVolume }
	 */
	public void setNextGroupPercentage(final PercentageAndVolume value)
	{
		this.nextGroupPercentage = value;
	}

	/**
	 * Gets the value of the qualifiedLegs property.
	 */
	public int getQualifiedLegs()
	{
		return qualifiedLegs;
	}

	/**
	 * Sets the value of the qualifiedLegs property.
	 */
	public void setQualifiedLegs(final int value)
	{
		this.qualifiedLegs = value;
	}

	/**
	 * Gets the value of the internationalQualifiedLegs property.
	 */
	public int getInternationalQualifiedLegs()
	{
		return internationalQualifiedLegs;
	}

	/**
	 * Sets the value of the internationalQualifiedLegs property.
	 */
	public void setInternationalQualifiedLegs(final int value)
	{
		this.internationalQualifiedLegs = value;
	}

	/**
	 * Gets the value of the fosterQualifiedLegs property.
	 */
	public int getFosterQualifiedLegs()
	{
		return fosterQualifiedLegs;
	}

	/**
	 * Sets the value of the fosterQualifiedLegs property.
	 */
	public void setFosterQualifiedLegs(final int value)
	{
		this.fosterQualifiedLegs = value;
	}

	/**
	 * @return internationalSponsorABO
	 */
	public Abo getInternationalSponsorABO()
	{
		return internationalSponsorABO;
	}

	/**
	 * @param value
	 */
	public void setInternationalSponsorABO(final Abo value)
	{
		this.internationalSponsorABO = value;
	}

	/**
	 * @return inMarketQualifiedLegs
	 */
	public int getInMarketQualifiedLegs()
	{
		return inMarketQualifiedLegs;
	}

	/**
	 * @param inMarketQualifiedLegs the inMarketQualifiedLegs to set
	 */
	public void setInMarketQualifiedLegs(final int inMarketQualifiedLegs)
	{
		this.inMarketQualifiedLegs = inMarketQualifiedLegs;
	}

	/**
	 * @return the businessNatureCode
	 */
	public String getBusinessNatureCode()
	{
		return businessNatureCode;
	}

	/**
	 * @param businessNatureCode the businessNatureCode to set
	 */
	public void setBusinessNatureCode(final String businessNatureCode)
	{
		this.businessNatureCode = businessNatureCode;
	}

}
