//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.25 at 07:43:28 PM IST 
//


package com.amway.integration.cis.los.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Created by aiu0256 on 5/22/15.
 * <p/>
 * <p/>
 * <p/>
 * Java class for percentageAndVolume complex type.
 * <p/>
 * <p/>
 * The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="percentageAndVolume">
 *   &lt;complexContent>
 *     &lt;extension base="{}percentage">
 *       &lt;sequence>
 *         &lt;element name="Volume" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "percentageAndVolume", propOrder = { "volume" })
public class PercentageAndVolume extends Percentage
{

	@XmlElement(name = "Volume")
	protected String volume;

	/**
	 * Gets the value of the volume property.
	 *
	 * @return possible object is {@link String }
	 */
	public String getVolume()
	{
		return volume;
	}

	/**
	 * Sets the value of the volume property.
	 *
	 * @param value allowed object is {@link String }
	 */
	public void setVolume(final String value)
	{
		this.volume = value;
	}

}
